        ;; tamsyn.s
        ;;
        ;; Generated by snatch from Tamzen6x12r.bdf (Tamsyn lineage).
        ;; Font copyright (c) 2015 Scott Fial; permissive custom free license.
        ;; Decoded font blob (single-label layout).
        .module zx_tamsyn

        .globl _zx_tamsyn

        .area _CONST
_zx_tamsyn::
        ;; font header
        .db 1                   ; font flags (bit0 proportional, bit1 offsets_be)
        .db 32                  ; first ascii
        .db 127                 ; last ascii
        .db 3                   ; empty_width
        .db 6                   ; max_glyph_width
        .db 12                  ; glyph_height
        .db 1                   ; advance
        .db 0                   ; descent

        ;; glpyh offsets
        .dw 0x00C8, 0x00CD, 0x00DE, 0x00EF, 0x0100, 0x0111, 0x0122, 0x0133
        .dw 0x0144, 0x0155, 0x0166, 0x0177, 0x0188, 0x0199, 0x01AA, 0x01BB
        .dw 0x01CC, 0x01DD, 0x01EE, 0x01FF, 0x0210, 0x0221, 0x0232, 0x0243
        .dw 0x0254, 0x0265, 0x0276, 0x0287, 0x0298, 0x02A9, 0x02BA, 0x02CB
        .dw 0x02DC, 0x02ED, 0x02FE, 0x030F, 0x0320, 0x0331, 0x0342, 0x0353
        .dw 0x0364, 0x0375, 0x0386, 0x0397, 0x03A8, 0x03B9, 0x03CA, 0x03DB
        .dw 0x03EC, 0x03FD, 0x040E, 0x041F, 0x0430, 0x0441, 0x0452, 0x0463
        .dw 0x0474, 0x0485, 0x0496, 0x04A7, 0x04B8, 0x04C9, 0x04DA, 0x04EB
        .dw 0x04FC, 0x050D, 0x051E, 0x052F, 0x0540, 0x0551, 0x0562, 0x0573
        .dw 0x0584, 0x0595, 0x05A6, 0x05B7, 0x05C8, 0x05D9, 0x05EA, 0x05FB
        .dw 0x060C, 0x061D, 0x062E, 0x063F, 0x0650, 0x0661, 0x0672, 0x0683
        .dw 0x0694, 0x06A5, 0x06B6, 0x06C7, 0x06D8, 0x06E9, 0x06FA, 0x070B

        ;; ascii 32: ' '
        .db 0                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 0                   ; width
        .db 12                  ; height
        .dw 0                 ; size (bytes)
        ;; ascii 33: '!'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 3                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00100000 ; row 1
        .db 0b00100000 ; row 2
        .db 0b00100000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b00000000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 34: '"'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b01010000 ; row 1
        .db 0b01010000 ; row 2
        .db 0b01010000 ; row 3
        .db 0b00000000 ; row 4
        .db 0b00000000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b00000000 ; row 7
        .db 0b00000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 35: '#'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b01010000 ; row 1
        .db 0b01010000 ; row 2
        .db 0b11111000 ; row 3
        .db 0b01010000 ; row 4
        .db 0b01010000 ; row 5
        .db 0b11111000 ; row 6
        .db 0b01010000 ; row 7
        .db 0b01010000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 36: '$'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00010000 ; row 0
        .db 0b00010000 ; row 1
        .db 0b00111000 ; row 2
        .db 0b01000000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b00010000 ; row 5
        .db 0b00001000 ; row 6
        .db 0b01110000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00100000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 37: '%'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b01000000 ; row 1
        .db 0b10100000 ; row 2
        .db 0b10101000 ; row 3
        .db 0b01010000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b01010000 ; row 6
        .db 0b10101000 ; row 7
        .db 0b00101000 ; row 8
        .db 0b00010000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 38: '&'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b01000000 ; row 1
        .db 0b10100000 ; row 2
        .db 0b10100000 ; row 3
        .db 0b01000000 ; row 4
        .db 0b10101000 ; row 5
        .db 0b10010000 ; row 6
        .db 0b10010000 ; row 7
        .db 0b01101000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 39: '''
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 3                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00100000 ; row 1
        .db 0b00100000 ; row 2
        .db 0b00100000 ; row 3
        .db 0b00000000 ; row 4
        .db 0b00000000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b00000000 ; row 7
        .db 0b00000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 40: '('
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00010000 ; row 1
        .db 0b00100000 ; row 2
        .db 0b00100000 ; row 3
        .db 0b01000000 ; row 4
        .db 0b01000000 ; row 5
        .db 0b01000000 ; row 6
        .db 0b01000000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00100000 ; row 9
        .db 0b00010000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 41: ')'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b01000000 ; row 1
        .db 0b00100000 ; row 2
        .db 0b00100000 ; row 3
        .db 0b00010000 ; row 4
        .db 0b00010000 ; row 5
        .db 0b00010000 ; row 6
        .db 0b00010000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00100000 ; row 9
        .db 0b01000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 42: '*'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00100000 ; row 3
        .db 0b10101000 ; row 4
        .db 0b01110000 ; row 5
        .db 0b10101000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b00000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 43: '+'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00100000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b11111000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b00000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 44: ','
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 3                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b00000000 ; row 4
        .db 0b00000000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b01100000 ; row 7
        .db 0b01100000 ; row 8
        .db 0b00100000 ; row 9
        .db 0b01000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 45: '-'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b00000000 ; row 4
        .db 0b11111000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b00000000 ; row 7
        .db 0b00000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 46: '.'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 3                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b00000000 ; row 4
        .db 0b00000000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b01100000 ; row 7
        .db 0b01100000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 47: '/'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00010000 ; row 2
        .db 0b00010000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b01000000 ; row 6
        .db 0b01000000 ; row 7
        .db 0b10000000 ; row 8
        .db 0b10000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 48: '0'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b01110000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10011000 ; row 4
        .db 0b10101000 ; row 5
        .db 0b11001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 49: '1'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00100000 ; row 2
        .db 0b01100000 ; row 3
        .db 0b10100000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b11111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 50: '2'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b01110000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b00001000 ; row 4
        .db 0b00010000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b01000000 ; row 7
        .db 0b11111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 51: '3'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b11111000 ; row 2
        .db 0b00001000 ; row 3
        .db 0b00010000 ; row 4
        .db 0b00110000 ; row 5
        .db 0b00001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 52: '4'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00010000 ; row 2
        .db 0b00110000 ; row 3
        .db 0b01010000 ; row 4
        .db 0b10010000 ; row 5
        .db 0b11111000 ; row 6
        .db 0b00010000 ; row 7
        .db 0b00010000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 53: '5'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b11111000 ; row 2
        .db 0b10000000 ; row 3
        .db 0b11110000 ; row 4
        .db 0b00001000 ; row 5
        .db 0b00001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 54: '6'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00110000 ; row 2
        .db 0b01000000 ; row 3
        .db 0b10000000 ; row 4
        .db 0b11110000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 55: '7'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b11111000 ; row 2
        .db 0b00001000 ; row 3
        .db 0b00010000 ; row 4
        .db 0b00010000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 56: '8'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b01110000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b01110000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 57: '9'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b01110000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b01111000 ; row 5
        .db 0b00001000 ; row 6
        .db 0b00010000 ; row 7
        .db 0b01100000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 58: ':'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 3                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b01100000 ; row 3
        .db 0b01100000 ; row 4
        .db 0b00000000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b01100000 ; row 7
        .db 0b01100000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 59: ';'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 3                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b01100000 ; row 3
        .db 0b01100000 ; row 4
        .db 0b00000000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b01100000 ; row 7
        .db 0b01100000 ; row 8
        .db 0b00100000 ; row 9
        .db 0b01000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 60: '<'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00001000 ; row 2
        .db 0b00010000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b01000000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00010000 ; row 7
        .db 0b00001000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 61: '='
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b11111000 ; row 4
        .db 0b00000000 ; row 5
        .db 0b11111000 ; row 6
        .db 0b00000000 ; row 7
        .db 0b00000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 62: '>'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10000000 ; row 2
        .db 0b01000000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b00010000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b01000000 ; row 7
        .db 0b10000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 63: '?'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b01110000 ; row 1
        .db 0b10001000 ; row 2
        .db 0b00001000 ; row 3
        .db 0b00010000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b00000000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 64: '@'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b01110000 ; row 1
        .db 0b10001000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10011000 ; row 4
        .db 0b10101000 ; row 5
        .db 0b10111000 ; row 6
        .db 0b10000000 ; row 7
        .db 0b10000000 ; row 8
        .db 0b01111000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 65: 'A'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00100000 ; row 2
        .db 0b01010000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b11111000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b10001000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 66: 'B'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b11110000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b11110000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b11110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 67: 'C'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00111000 ; row 2
        .db 0b01000000 ; row 3
        .db 0b10000000 ; row 4
        .db 0b10000000 ; row 5
        .db 0b10000000 ; row 6
        .db 0b01000000 ; row 7
        .db 0b00111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 68: 'D'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b11110000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10010000 ; row 7
        .db 0b11100000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 69: 'E'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b11111000 ; row 2
        .db 0b10000000 ; row 3
        .db 0b10000000 ; row 4
        .db 0b11110000 ; row 5
        .db 0b10000000 ; row 6
        .db 0b10000000 ; row 7
        .db 0b11111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 70: 'F'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b11111000 ; row 2
        .db 0b10000000 ; row 3
        .db 0b10000000 ; row 4
        .db 0b11110000 ; row 5
        .db 0b10000000 ; row 6
        .db 0b10000000 ; row 7
        .db 0b10000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 71: 'G'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00111000 ; row 2
        .db 0b01000000 ; row 3
        .db 0b10000000 ; row 4
        .db 0b10011000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b01001000 ; row 7
        .db 0b00111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 72: 'H'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10001000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b11111000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b10001000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 73: 'I'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b01110000 ; row 2
        .db 0b00100000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 74: 'J'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00001000 ; row 2
        .db 0b00001000 ; row 3
        .db 0b00001000 ; row 4
        .db 0b00001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 75: 'K'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10001000 ; row 2
        .db 0b10010000 ; row 3
        .db 0b10100000 ; row 4
        .db 0b11000000 ; row 5
        .db 0b10100000 ; row 6
        .db 0b10010000 ; row 7
        .db 0b10001000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 76: 'L'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10000000 ; row 2
        .db 0b10000000 ; row 3
        .db 0b10000000 ; row 4
        .db 0b10000000 ; row 5
        .db 0b10000000 ; row 6
        .db 0b10000000 ; row 7
        .db 0b11111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 77: 'M'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10001000 ; row 2
        .db 0b11011000 ; row 3
        .db 0b10101000 ; row 4
        .db 0b10101000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b10001000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 78: 'N'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10001000 ; row 2
        .db 0b11001000 ; row 3
        .db 0b10101000 ; row 4
        .db 0b10011000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b10001000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 79: 'O'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b01110000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 80: 'P'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b11110000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b11110000 ; row 5
        .db 0b10000000 ; row 6
        .db 0b10000000 ; row 7
        .db 0b10000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 81: 'Q'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b01110000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00010000 ; row 9
        .db 0b00001000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 82: 'R'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b11110000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b11110000 ; row 5
        .db 0b10100000 ; row 6
        .db 0b10010000 ; row 7
        .db 0b10001000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 83: 'S'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b01111000 ; row 2
        .db 0b10000000 ; row 3
        .db 0b10000000 ; row 4
        .db 0b01110000 ; row 5
        .db 0b00001000 ; row 6
        .db 0b00001000 ; row 7
        .db 0b11110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 84: 'T'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b11111000 ; row 2
        .db 0b00100000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 85: 'U'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10001000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 86: 'V'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10001000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b01010000 ; row 5
        .db 0b01010000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 87: 'W'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10001000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b10101000 ; row 5
        .db 0b10101000 ; row 6
        .db 0b10101000 ; row 7
        .db 0b11011000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 88: 'X'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10001000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b01010000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b01010000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b10001000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 89: 'Y'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10001000 ; row 2
        .db 0b10001000 ; row 3
        .db 0b01010000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 90: 'Z'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b11111000 ; row 2
        .db 0b00010000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b01000000 ; row 6
        .db 0b01000000 ; row 7
        .db 0b11111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 91: '['
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b01110000 ; row 1
        .db 0b01000000 ; row 2
        .db 0b01000000 ; row 3
        .db 0b01000000 ; row 4
        .db 0b01000000 ; row 5
        .db 0b01000000 ; row 6
        .db 0b01000000 ; row 7
        .db 0b01000000 ; row 8
        .db 0b01000000 ; row 9
        .db 0b01110000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 92: '\'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10000000 ; row 2
        .db 0b10000000 ; row 3
        .db 0b01000000 ; row 4
        .db 0b01000000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b00010000 ; row 8
        .db 0b00010000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 93: ']'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b01110000 ; row 1
        .db 0b00010000 ; row 2
        .db 0b00010000 ; row 3
        .db 0b00010000 ; row 4
        .db 0b00010000 ; row 5
        .db 0b00010000 ; row 6
        .db 0b00010000 ; row 7
        .db 0b00010000 ; row 8
        .db 0b00010000 ; row 9
        .db 0b01110000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 94: '^'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00100000 ; row 2
        .db 0b01010000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b00000000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b00000000 ; row 7
        .db 0b00000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 95: '_'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 6                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b00000000 ; row 4
        .db 0b00000000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b00000000 ; row 7
        .db 0b00000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b11111100 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 96: '`'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b01000000 ; row 1
        .db 0b00100000 ; row 2
        .db 0b00010000 ; row 3
        .db 0b00000000 ; row 4
        .db 0b00000000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b00000000 ; row 7
        .db 0b00000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 97: 'a'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b01110000 ; row 4
        .db 0b00001000 ; row 5
        .db 0b01111000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 98: 'b'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10000000 ; row 2
        .db 0b10000000 ; row 3
        .db 0b11110000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b11110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 99: 'c'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b01111000 ; row 4
        .db 0b10000000 ; row 5
        .db 0b10000000 ; row 6
        .db 0b10000000 ; row 7
        .db 0b01111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 100: 'd'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00001000 ; row 2
        .db 0b00001000 ; row 3
        .db 0b01111000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 101: 'e'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b01110000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b11111000 ; row 6
        .db 0b10000000 ; row 7
        .db 0b01111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 102: 'f'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00111000 ; row 2
        .db 0b01000000 ; row 3
        .db 0b11111000 ; row 4
        .db 0b01000000 ; row 5
        .db 0b01000000 ; row 6
        .db 0b01000000 ; row 7
        .db 0b01000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 103: 'g'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b01111000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01111000 ; row 8
        .db 0b00001000 ; row 9
        .db 0b01110000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 104: 'h'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10000000 ; row 2
        .db 0b10000000 ; row 3
        .db 0b11110000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b10001000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 105: 'i'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00100000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b01100000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 106: 'j'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00010000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b00110000 ; row 4
        .db 0b00010000 ; row 5
        .db 0b00010000 ; row 6
        .db 0b00010000 ; row 7
        .db 0b00010000 ; row 8
        .db 0b00010000 ; row 9
        .db 0b01100000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 107: 'k'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b10000000 ; row 2
        .db 0b10000000 ; row 3
        .db 0b10010000 ; row 4
        .db 0b10100000 ; row 5
        .db 0b11100000 ; row 6
        .db 0b10010000 ; row 7
        .db 0b10001000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 108: 'l'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 4                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b01100000 ; row 2
        .db 0b00100000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 109: 'm'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b11011000 ; row 4
        .db 0b10101000 ; row 5
        .db 0b10101000 ; row 6
        .db 0b10101000 ; row 7
        .db 0b10101000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 110: 'n'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b11110000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b10001000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 111: 'o'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b01110000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 112: 'p'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b11110000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b11110000 ; row 8
        .db 0b10000000 ; row 9
        .db 0b10000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 113: 'q'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b01111000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01111000 ; row 8
        .db 0b00001000 ; row 9
        .db 0b00001000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 114: 'r'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b10111000 ; row 4
        .db 0b11000000 ; row 5
        .db 0b10000000 ; row 6
        .db 0b10000000 ; row 7
        .db 0b10000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 115: 's'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b01111000 ; row 4
        .db 0b10000000 ; row 5
        .db 0b01110000 ; row 6
        .db 0b00001000 ; row 7
        .db 0b11110000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 116: 't'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b01000000 ; row 3
        .db 0b11111000 ; row 4
        .db 0b01000000 ; row 5
        .db 0b01000000 ; row 6
        .db 0b01000000 ; row 7
        .db 0b00111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 117: 'u'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b10001000 ; row 7
        .db 0b01111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 118: 'v'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10001000 ; row 6
        .db 0b01010000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 119: 'w'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b10101000 ; row 6
        .db 0b10101000 ; row 7
        .db 0b11011000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 120: 'x'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b01010000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b01010000 ; row 7
        .db 0b10001000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 121: 'y'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b10001000 ; row 4
        .db 0b10001000 ; row 5
        .db 0b01010000 ; row 6
        .db 0b01010000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00100000 ; row 9
        .db 0b11000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 122: 'z'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b00000000 ; row 2
        .db 0b00000000 ; row 3
        .db 0b11111000 ; row 4
        .db 0b00010000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b01000000 ; row 7
        .db 0b11111000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 123: '{'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00011000 ; row 0
        .db 0b00100000 ; row 1
        .db 0b00100000 ; row 2
        .db 0b00100000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b11000000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00100000 ; row 9
        .db 0b00011000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 124: '|'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 3                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00100000 ; row 1
        .db 0b00100000 ; row 2
        .db 0b00100000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b00100000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00100000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 125: '}'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b11000000 ; row 0
        .db 0b00100000 ; row 1
        .db 0b00100000 ; row 2
        .db 0b00100000 ; row 3
        .db 0b00100000 ; row 4
        .db 0b00011000 ; row 5
        .db 0b00100000 ; row 6
        .db 0b00100000 ; row 7
        .db 0b00100000 ; row 8
        .db 0b00100000 ; row 9
        .db 0b11000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 126: '~'
        .db 1                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 5                   ; width
        .db 12                  ; height
        .dw 12                 ; size (bytes)
        .db 0b00000000 ; row 0
        .db 0b00000000 ; row 1
        .db 0b01001000 ; row 2
        .db 0b10101000 ; row 3
        .db 0b10010000 ; row 4
        .db 0b00000000 ; row 5
        .db 0b00000000 ; row 6
        .db 0b00000000 ; row 7
        .db 0b00000000 ; row 8
        .db 0b00000000 ; row 9
        .db 0b00000000 ; row 10
        .db 0b00000000 ; row 11
        ;; ascii 127: <non standard>
        .db 0                   ; bmp_t signature (bits5-4 type, bits3-0 stride)
        .db 0                   ; width
        .db 12                  ; height
        .dw 0                 ; size (bytes)
