X_MODEL ?= M

ifneq ($(filter S s,$(X_MODEL)),)
X_MODEL_NAME := S
X_MODEL_SUFFIX := s
X_MODEL_LIBC_FLOAT_DEFAULT := 0
X_MODEL_LIBC_DOUBLE_DEFAULT := 0
X_MODEL_LIBC_LONG_DEFAULT := 0
X_MODEL_LIBC_LONGLONG_DEFAULT := 0
X_MODEL_LIBC_STDIO_FLOAT_DEFAULT := 0
else ifneq ($(filter M m,$(X_MODEL)),)
X_MODEL_NAME := M
X_MODEL_SUFFIX := m
X_MODEL_LIBC_FLOAT_DEFAULT := 1
X_MODEL_LIBC_DOUBLE_DEFAULT := 0
X_MODEL_LIBC_LONG_DEFAULT := 1
X_MODEL_LIBC_LONGLONG_DEFAULT := 0
X_MODEL_LIBC_STDIO_FLOAT_DEFAULT := 0
else ifneq ($(filter L l,$(X_MODEL)),)
X_MODEL_NAME := L
X_MODEL_SUFFIX := l
X_MODEL_LIBC_FLOAT_DEFAULT := 1
X_MODEL_LIBC_DOUBLE_DEFAULT := 1
X_MODEL_LIBC_LONG_DEFAULT := 1
X_MODEL_LIBC_LONGLONG_DEFAULT := 1
X_MODEL_LIBC_STDIO_FLOAT_DEFAULT := 1
else
$(error X_MODEL must be S, M, or L)
endif
