unsigned f0_0_1(unsigned *p){p++;unsigned _BitInt(1) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_0_2(unsigned *p){p++;unsigned _BitInt(2) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_0_3(unsigned *p){p++;unsigned _BitInt(3) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_0_4(unsigned *p){p++;unsigned _BitInt(4) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_0_5(unsigned *p){p++;unsigned _BitInt(5) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_0_6(unsigned *p){p++;unsigned _BitInt(6) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_0_7(unsigned *p){p++;unsigned _BitInt(7) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_0_8(unsigned *p){p++;unsigned _BitInt(8) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_1_2(unsigned *p){p++;_BitInt(2) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_1_3(unsigned *p){p++;_BitInt(3) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_1_4(unsigned *p){p++;_BitInt(4) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_1_5(unsigned *p){p++;_BitInt(5) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_1_6(unsigned *p){p++;_BitInt(6) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_1_7(unsigned *p){p++;_BitInt(7) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f0_1_8(unsigned *p){p++;_BitInt(8) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_0_1(volatile unsigned *p){p++;unsigned _BitInt(1) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_0_2(volatile unsigned *p){p++;unsigned _BitInt(2) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_0_3(volatile unsigned *p){p++;unsigned _BitInt(3) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_0_4(volatile unsigned *p){p++;unsigned _BitInt(4) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_0_5(volatile unsigned *p){p++;unsigned _BitInt(5) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_0_6(volatile unsigned *p){p++;unsigned _BitInt(6) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_0_7(volatile unsigned *p){p++;unsigned _BitInt(7) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_0_8(volatile unsigned *p){p++;unsigned _BitInt(8) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_1_2(volatile unsigned *p){p++;_BitInt(2) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_1_3(volatile unsigned *p){p++;_BitInt(3) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_1_4(volatile unsigned *p){p++;_BitInt(4) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_1_5(volatile unsigned *p){p++;_BitInt(5) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_1_6(volatile unsigned *p){p++;_BitInt(6) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_1_7(volatile unsigned *p){p++;_BitInt(7) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f1_1_8(volatile unsigned *p){p++;_BitInt(8) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_0_1(unsigned char *p){p++;unsigned _BitInt(1) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_0_2(unsigned char *p){p++;unsigned _BitInt(2) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_0_3(unsigned char *p){p++;unsigned _BitInt(3) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_0_4(unsigned char *p){p++;unsigned _BitInt(4) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_0_5(unsigned char *p){p++;unsigned _BitInt(5) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_0_6(unsigned char *p){p++;unsigned _BitInt(6) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_0_7(unsigned char *p){p++;unsigned _BitInt(7) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_0_8(unsigned char *p){p++;unsigned _BitInt(8) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_1_2(unsigned char *p){p++;_BitInt(2) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_1_3(unsigned char *p){p++;_BitInt(3) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_1_4(unsigned char *p){p++;_BitInt(4) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_1_5(unsigned char *p){p++;_BitInt(5) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_1_6(unsigned char *p){p++;_BitInt(6) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_1_7(unsigned char *p){p++;_BitInt(7) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f2_1_8(unsigned char *p){p++;_BitInt(8) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_0_1(volatile unsigned char *p){p++;unsigned _BitInt(1) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_0_2(volatile unsigned char *p){p++;unsigned _BitInt(2) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_0_3(volatile unsigned char *p){p++;unsigned _BitInt(3) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_0_4(volatile unsigned char *p){p++;unsigned _BitInt(4) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_0_5(volatile unsigned char *p){p++;unsigned _BitInt(5) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_0_6(volatile unsigned char *p){p++;unsigned _BitInt(6) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_0_7(volatile unsigned char *p){p++;unsigned _BitInt(7) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_0_8(volatile unsigned char *p){p++;unsigned _BitInt(8) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_1_2(volatile unsigned char *p){p++;_BitInt(2) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_1_3(volatile unsigned char *p){p++;_BitInt(3) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_1_4(volatile unsigned char *p){p++;_BitInt(4) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_1_5(volatile unsigned char *p){p++;_BitInt(5) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_1_6(volatile unsigned char *p){p++;_BitInt(6) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_1_7(volatile unsigned char *p){p++;_BitInt(7) x=*(p-1);return (unsigned)x+(unsigned)p;}
unsigned f3_1_8(volatile unsigned char *p){p++;_BitInt(8) x=*(p-1);return (unsigned)x+(unsigned)p;}
volatile unsigned * volatile cursor;
unsigned cursor_case(void){cursor++;unsigned char x=*(cursor-1);return x+(unsigned)cursor;}
unsigned local_alias(void){unsigned char *p=(unsigned char *)&p;p++;unsigned char x=*(p-1);return x!=(unsigned char)(unsigned)p;}
unsigned char *global_cursor;
unsigned global_alias(void){global_cursor=(unsigned char *)&global_cursor;global_cursor++;unsigned char x=*(global_cursor-1);return x!=(unsigned char)(unsigned)global_cursor;}
