#!/usr/bin/env python3
"""Generate the compact YOS font payload from its readable assembly source."""

# GPL-2.0 License (see: LICENSE)
# Copyright (C) 2026 tomaz stih

from pathlib import Path
import re
import sys


def values(source: str) -> list[int]:
    source = source[source.index(";; glyph 0x20"):]
    result: list[int] = []
    for kind, body in re.findall(r"^\s*\.(db|dw)\s+([^;]+)", source, re.M):
        for item in body.split(","):
            value = int(item.strip(), 0)
            result.append(value & 0xff)
            if kind == "dw":
                result.append((value >> 8) & 0xff)
    return result


def pack(records: list[int]) -> tuple[list[int], list[int]]:
    widths: list[tuple[int, int]] = []
    packed: list[int] = []
    pos = 0
    for code in range(0x20, 0x80):
        signature, width, height = records[pos:pos + 3]
        size = records[pos + 3] | records[pos + 4] << 8
        bitmap = records[pos + 5:pos + 5 + size]
        pos += 5 + size
        if code == 0x20:
            assert (signature, width, height, size) == (0, 0, 8, 0)
            continue
        assert signature == 0 and height == 8 and size == 8
        if width != 5:
            widths.append((code, width))
        bits = []
        for row in bitmap:
            bits.extend((row >> (7 - bit)) & 1 for bit in range(width))
        for offset in range(0, len(bits), 8):
            byte = 0
            for bit in bits[offset:offset + 8]:
                byte = byte << 1 | bit
            packed.append(byte)
    exceptions: list[int] = []
    for index, (code, width) in enumerate(widths):
        next_code = widths[index + 1][0] if index + 1 < len(widths) else code
        exceptions.extend((width, next_code - code))
    assert pos == len(records) and len(widths) == 21 and len(packed) == 432
    return exceptions, packed


def main() -> None:
    source = Path(sys.argv[1]).read_text()
    widths, packed = pack(values(source))
    lines = [
        "; Generated by y/scripts/pack_font.py; do not edit.",
        ".module _gpx_font_packed",
        ".optsdcc -mz80 sdcccall(1)",
        ".globl __gpx_font_widths",
        ".globl __gpx_font_packed",
        ".area _CODE",
        "__gpx_font_widths::",
    ]
    for offset in range(0, len(widths), 18):
        lines.append("        .db " + ",".join(
            f"0x{byte:02x}" for byte in widths[offset:offset + 18]))
    lines += [
        "__gpx_font_packed::",
    ]
    for offset in range(0, len(packed), 18):
        lines.append("        .db " + ",".join(
            f"0x{byte:02x}" for byte in packed[offset:offset + 18]))
    Path(sys.argv[2]).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
