/*
 * Simulator of microcontrollers (itabcl.h)
 *
 * Copyright (C) 1999 Daniel
 * 
 * To contact author send email to dr.dkdb@gmail.com
 *
 */

/*
  This file is part of microcontroller simulator: ucsim.

  UCSIM is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  UCSIM is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with UCSIM; see the file COPYING.  If not, write to the Free
  Software Foundation, 59 Temple Place - Suite 330, Boston, MA
  02111-1307, USA.
*/

#ifndef SIM_ITAB_HEADER
#define SIM_ITAB_HEADER

#include "pobjcl.h"
#include "stypes.h"


class cl_itab: public cl_base
{
 public:
  int def_result;
  int (cl_itab::*uc_itab[3*256])(t_mem code);
 public:
  cl_itab(void);
 public:
  virtual int invalid_instruction(t_mem code) { return resINV; }
  virtual int instruction_00(t_mem code) { return def_result; }
  virtual int instruction_01(t_mem code) { return def_result; }
  virtual int instruction_02(t_mem code) { return def_result; }
  virtual int instruction_03(t_mem code) { return def_result; }
  virtual int instruction_04(t_mem code) { return def_result; }
  virtual int instruction_05(t_mem code) { return def_result; }
  virtual int instruction_06(t_mem code) { return def_result; }
  virtual int instruction_07(t_mem code) { return def_result; }
  virtual int instruction_08(t_mem code) { return def_result; }
  virtual int instruction_09(t_mem code) { return def_result; }
  virtual int instruction_0a(t_mem code) { return def_result; }
  virtual int instruction_0b(t_mem code) { return def_result; }
  virtual int instruction_0c(t_mem code) { return def_result; }
  virtual int instruction_0d(t_mem code) { return def_result; }
  virtual int instruction_0e(t_mem code) { return def_result; }
  virtual int instruction_0f(t_mem code) { return def_result; }
  virtual int instruction_10(t_mem code) { return def_result; }
  virtual int instruction_11(t_mem code) { return def_result; }
  virtual int instruction_12(t_mem code) { return def_result; }
  virtual int instruction_13(t_mem code) { return def_result; }
  virtual int instruction_14(t_mem code) { return def_result; }
  virtual int instruction_15(t_mem code) { return def_result; }
  virtual int instruction_16(t_mem code) { return def_result; }
  virtual int instruction_17(t_mem code) { return def_result; }
  virtual int instruction_18(t_mem code) { return def_result; }
  virtual int instruction_19(t_mem code) { return def_result; }
  virtual int instruction_1a(t_mem code) { return def_result; }
  virtual int instruction_1b(t_mem code) { return def_result; }
  virtual int instruction_1c(t_mem code) { return def_result; }
  virtual int instruction_1d(t_mem code) { return def_result; }
  virtual int instruction_1e(t_mem code) { return def_result; }
  virtual int instruction_1f(t_mem code) { return def_result; }
  virtual int instruction_20(t_mem code) { return def_result; }
  virtual int instruction_21(t_mem code) { return def_result; }
  virtual int instruction_22(t_mem code) { return def_result; }
  virtual int instruction_23(t_mem code) { return def_result; }
  virtual int instruction_24(t_mem code) { return def_result; }
  virtual int instruction_25(t_mem code) { return def_result; }
  virtual int instruction_26(t_mem code) { return def_result; }
  virtual int instruction_27(t_mem code) { return def_result; }
  virtual int instruction_28(t_mem code) { return def_result; }
  virtual int instruction_29(t_mem code) { return def_result; }
  virtual int instruction_2a(t_mem code) { return def_result; }
  virtual int instruction_2b(t_mem code) { return def_result; }
  virtual int instruction_2c(t_mem code) { return def_result; }
  virtual int instruction_2d(t_mem code) { return def_result; }
  virtual int instruction_2e(t_mem code) { return def_result; }
  virtual int instruction_2f(t_mem code) { return def_result; }
  virtual int instruction_30(t_mem code) { return def_result; }
  virtual int instruction_31(t_mem code) { return def_result; }
  virtual int instruction_32(t_mem code) { return def_result; }
  virtual int instruction_33(t_mem code) { return def_result; }
  virtual int instruction_34(t_mem code) { return def_result; }
  virtual int instruction_35(t_mem code) { return def_result; }
  virtual int instruction_36(t_mem code) { return def_result; }
  virtual int instruction_37(t_mem code) { return def_result; }
  virtual int instruction_38(t_mem code) { return def_result; }
  virtual int instruction_39(t_mem code) { return def_result; }
  virtual int instruction_3a(t_mem code) { return def_result; }
  virtual int instruction_3b(t_mem code) { return def_result; }
  virtual int instruction_3c(t_mem code) { return def_result; }
  virtual int instruction_3d(t_mem code) { return def_result; }
  virtual int instruction_3e(t_mem code) { return def_result; }
  virtual int instruction_3f(t_mem code) { return def_result; }
  virtual int instruction_40(t_mem code) { return def_result; }
  virtual int instruction_41(t_mem code) { return def_result; }
  virtual int instruction_42(t_mem code) { return def_result; }
  virtual int instruction_43(t_mem code) { return def_result; }
  virtual int instruction_44(t_mem code) { return def_result; }
  virtual int instruction_45(t_mem code) { return def_result; }
  virtual int instruction_46(t_mem code) { return def_result; }
  virtual int instruction_47(t_mem code) { return def_result; }
  virtual int instruction_48(t_mem code) { return def_result; }
  virtual int instruction_49(t_mem code) { return def_result; }
  virtual int instruction_4a(t_mem code) { return def_result; }
  virtual int instruction_4b(t_mem code) { return def_result; }
  virtual int instruction_4c(t_mem code) { return def_result; }
  virtual int instruction_4d(t_mem code) { return def_result; }
  virtual int instruction_4e(t_mem code) { return def_result; }
  virtual int instruction_4f(t_mem code) { return def_result; }
  virtual int instruction_50(t_mem code) { return def_result; }
  virtual int instruction_51(t_mem code) { return def_result; }
  virtual int instruction_52(t_mem code) { return def_result; }
  virtual int instruction_53(t_mem code) { return def_result; }
  virtual int instruction_54(t_mem code) { return def_result; }
  virtual int instruction_55(t_mem code) { return def_result; }
  virtual int instruction_56(t_mem code) { return def_result; }
  virtual int instruction_57(t_mem code) { return def_result; }
  virtual int instruction_58(t_mem code) { return def_result; }
  virtual int instruction_59(t_mem code) { return def_result; }
  virtual int instruction_5a(t_mem code) { return def_result; }
  virtual int instruction_5b(t_mem code) { return def_result; }
  virtual int instruction_5c(t_mem code) { return def_result; }
  virtual int instruction_5d(t_mem code) { return def_result; }
  virtual int instruction_5e(t_mem code) { return def_result; }
  virtual int instruction_5f(t_mem code) { return def_result; }
  virtual int instruction_60(t_mem code) { return def_result; }
  virtual int instruction_61(t_mem code) { return def_result; }
  virtual int instruction_62(t_mem code) { return def_result; }
  virtual int instruction_63(t_mem code) { return def_result; }
  virtual int instruction_64(t_mem code) { return def_result; }
  virtual int instruction_65(t_mem code) { return def_result; }
  virtual int instruction_66(t_mem code) { return def_result; }
  virtual int instruction_67(t_mem code) { return def_result; }
  virtual int instruction_68(t_mem code) { return def_result; }
  virtual int instruction_69(t_mem code) { return def_result; }
  virtual int instruction_6a(t_mem code) { return def_result; }
  virtual int instruction_6b(t_mem code) { return def_result; }
  virtual int instruction_6c(t_mem code) { return def_result; }
  virtual int instruction_6d(t_mem code) { return def_result; }
  virtual int instruction_6e(t_mem code) { return def_result; }
  virtual int instruction_6f(t_mem code) { return def_result; }
  virtual int instruction_70(t_mem code) { return def_result; }
  virtual int instruction_71(t_mem code) { return def_result; }
  virtual int instruction_72(t_mem code) { return def_result; }
  virtual int instruction_73(t_mem code) { return def_result; }
  virtual int instruction_74(t_mem code) { return def_result; }
  virtual int instruction_75(t_mem code) { return def_result; }
  virtual int instruction_76(t_mem code) { return def_result; }
  virtual int instruction_77(t_mem code) { return def_result; }
  virtual int instruction_78(t_mem code) { return def_result; }
  virtual int instruction_79(t_mem code) { return def_result; }
  virtual int instruction_7a(t_mem code) { return def_result; }
  virtual int instruction_7b(t_mem code) { return def_result; }
  virtual int instruction_7c(t_mem code) { return def_result; }
  virtual int instruction_7d(t_mem code) { return def_result; }
  virtual int instruction_7e(t_mem code) { return def_result; }
  virtual int instruction_7f(t_mem code) { return def_result; }
  virtual int instruction_80(t_mem code) { return def_result; }
  virtual int instruction_81(t_mem code) { return def_result; }
  virtual int instruction_82(t_mem code) { return def_result; }
  virtual int instruction_83(t_mem code) { return def_result; }
  virtual int instruction_84(t_mem code) { return def_result; }
  virtual int instruction_85(t_mem code) { return def_result; }
  virtual int instruction_86(t_mem code) { return def_result; }
  virtual int instruction_87(t_mem code) { return def_result; }
  virtual int instruction_88(t_mem code) { return def_result; }
  virtual int instruction_89(t_mem code) { return def_result; }
  virtual int instruction_8a(t_mem code) { return def_result; }
  virtual int instruction_8b(t_mem code) { return def_result; }
  virtual int instruction_8c(t_mem code) { return def_result; }
  virtual int instruction_8d(t_mem code) { return def_result; }
  virtual int instruction_8e(t_mem code) { return def_result; }
  virtual int instruction_8f(t_mem code) { return def_result; }
  virtual int instruction_90(t_mem code) { return def_result; }
  virtual int instruction_91(t_mem code) { return def_result; }
  virtual int instruction_92(t_mem code) { return def_result; }
  virtual int instruction_93(t_mem code) { return def_result; }
  virtual int instruction_94(t_mem code) { return def_result; }
  virtual int instruction_95(t_mem code) { return def_result; }
  virtual int instruction_96(t_mem code) { return def_result; }
  virtual int instruction_97(t_mem code) { return def_result; }
  virtual int instruction_98(t_mem code) { return def_result; }
  virtual int instruction_99(t_mem code) { return def_result; }
  virtual int instruction_9a(t_mem code) { return def_result; }
  virtual int instruction_9b(t_mem code) { return def_result; }
  virtual int instruction_9c(t_mem code) { return def_result; }
  virtual int instruction_9d(t_mem code) { return def_result; }
  virtual int instruction_9e(t_mem code) { return def_result; }
  virtual int instruction_9f(t_mem code) { return def_result; }
  virtual int instruction_a0(t_mem code) { return def_result; }
  virtual int instruction_a1(t_mem code) { return def_result; }
  virtual int instruction_a2(t_mem code) { return def_result; }
  virtual int instruction_a3(t_mem code) { return def_result; }
  virtual int instruction_a4(t_mem code) { return def_result; }
  virtual int instruction_a5(t_mem code) { return def_result; }
  virtual int instruction_a6(t_mem code) { return def_result; }
  virtual int instruction_a7(t_mem code) { return def_result; }
  virtual int instruction_a8(t_mem code) { return def_result; }
  virtual int instruction_a9(t_mem code) { return def_result; }
  virtual int instruction_aa(t_mem code) { return def_result; }
  virtual int instruction_ab(t_mem code) { return def_result; }
  virtual int instruction_ac(t_mem code) { return def_result; }
  virtual int instruction_ad(t_mem code) { return def_result; }
  virtual int instruction_ae(t_mem code) { return def_result; }
  virtual int instruction_af(t_mem code) { return def_result; }
  virtual int instruction_b0(t_mem code) { return def_result; }
  virtual int instruction_b1(t_mem code) { return def_result; }
  virtual int instruction_b2(t_mem code) { return def_result; }
  virtual int instruction_b3(t_mem code) { return def_result; }
  virtual int instruction_b4(t_mem code) { return def_result; }
  virtual int instruction_b5(t_mem code) { return def_result; }
  virtual int instruction_b6(t_mem code) { return def_result; }
  virtual int instruction_b7(t_mem code) { return def_result; }
  virtual int instruction_b8(t_mem code) { return def_result; }
  virtual int instruction_b9(t_mem code) { return def_result; }
  virtual int instruction_ba(t_mem code) { return def_result; }
  virtual int instruction_bb(t_mem code) { return def_result; }
  virtual int instruction_bc(t_mem code) { return def_result; }
  virtual int instruction_bd(t_mem code) { return def_result; }
  virtual int instruction_be(t_mem code) { return def_result; }
  virtual int instruction_bf(t_mem code) { return def_result; }
  virtual int instruction_c0(t_mem code) { return def_result; }
  virtual int instruction_c1(t_mem code) { return def_result; }
  virtual int instruction_c2(t_mem code) { return def_result; }
  virtual int instruction_c3(t_mem code) { return def_result; }
  virtual int instruction_c4(t_mem code) { return def_result; }
  virtual int instruction_c5(t_mem code) { return def_result; }
  virtual int instruction_c6(t_mem code) { return def_result; }
  virtual int instruction_c7(t_mem code) { return def_result; }
  virtual int instruction_c8(t_mem code) { return def_result; }
  virtual int instruction_c9(t_mem code) { return def_result; }
  virtual int instruction_ca(t_mem code) { return def_result; }
  virtual int instruction_cb(t_mem code) { return def_result; }
  virtual int instruction_cc(t_mem code) { return def_result; }
  virtual int instruction_cd(t_mem code) { return def_result; }
  virtual int instruction_ce(t_mem code) { return def_result; }
  virtual int instruction_cf(t_mem code) { return def_result; }
  virtual int instruction_d0(t_mem code) { return def_result; }
  virtual int instruction_d1(t_mem code) { return def_result; }
  virtual int instruction_d2(t_mem code) { return def_result; }
  virtual int instruction_d3(t_mem code) { return def_result; }
  virtual int instruction_d4(t_mem code) { return def_result; }
  virtual int instruction_d5(t_mem code) { return def_result; }
  virtual int instruction_d6(t_mem code) { return def_result; }
  virtual int instruction_d7(t_mem code) { return def_result; }
  virtual int instruction_d8(t_mem code) { return def_result; }
  virtual int instruction_d9(t_mem code) { return def_result; }
  virtual int instruction_da(t_mem code) { return def_result; }
  virtual int instruction_db(t_mem code) { return def_result; }
  virtual int instruction_dc(t_mem code) { return def_result; }
  virtual int instruction_dd(t_mem code) { return def_result; }
  virtual int instruction_de(t_mem code) { return def_result; }
  virtual int instruction_df(t_mem code) { return def_result; }
  virtual int instruction_e0(t_mem code) { return def_result; }
  virtual int instruction_e1(t_mem code) { return def_result; }
  virtual int instruction_e2(t_mem code) { return def_result; }
  virtual int instruction_e3(t_mem code) { return def_result; }
  virtual int instruction_e4(t_mem code) { return def_result; }
  virtual int instruction_e5(t_mem code) { return def_result; }
  virtual int instruction_e6(t_mem code) { return def_result; }
  virtual int instruction_e7(t_mem code) { return def_result; }
  virtual int instruction_e8(t_mem code) { return def_result; }
  virtual int instruction_e9(t_mem code) { return def_result; }
  virtual int instruction_ea(t_mem code) { return def_result; }
  virtual int instruction_eb(t_mem code) { return def_result; }
  virtual int instruction_ec(t_mem code) { return def_result; }
  virtual int instruction_ed(t_mem code) { return def_result; }
  virtual int instruction_ee(t_mem code) { return def_result; }
  virtual int instruction_ef(t_mem code) { return def_result; }
  virtual int instruction_f0(t_mem code) { return def_result; }
  virtual int instruction_f1(t_mem code) { return def_result; }
  virtual int instruction_f2(t_mem code) { return def_result; }
  virtual int instruction_f3(t_mem code) { return def_result; }
  virtual int instruction_f4(t_mem code) { return def_result; }
  virtual int instruction_f5(t_mem code) { return def_result; }
  virtual int instruction_f6(t_mem code) { return def_result; }
  virtual int instruction_f7(t_mem code) { return def_result; }
  virtual int instruction_f8(t_mem code) { return def_result; }
  virtual int instruction_f9(t_mem code) { return def_result; }
  virtual int instruction_fa(t_mem code) { return def_result; }
  virtual int instruction_fb(t_mem code) { return def_result; }
  virtual int instruction_fc(t_mem code) { return def_result; }
  virtual int instruction_fd(t_mem code) { return def_result; }
  virtual int instruction_fe(t_mem code) { return def_result; }
  virtual int instruction_ff(t_mem code) { return def_result; }

  virtual int instruction_100(t_mem code) { return def_result; }
  virtual int instruction_101(t_mem code) { return def_result; }
  virtual int instruction_102(t_mem code) { return def_result; }
  virtual int instruction_103(t_mem code) { return def_result; }
  virtual int instruction_104(t_mem code) { return def_result; }
  virtual int instruction_105(t_mem code) { return def_result; }
  virtual int instruction_106(t_mem code) { return def_result; }
  virtual int instruction_107(t_mem code) { return def_result; }
  virtual int instruction_108(t_mem code) { return def_result; }
  virtual int instruction_109(t_mem code) { return def_result; }
  virtual int instruction_10a(t_mem code) { return def_result; }
  virtual int instruction_10b(t_mem code) { return def_result; }
  virtual int instruction_10c(t_mem code) { return def_result; }
  virtual int instruction_10d(t_mem code) { return def_result; }
  virtual int instruction_10e(t_mem code) { return def_result; }
  virtual int instruction_10f(t_mem code) { return def_result; }
  virtual int instruction_110(t_mem code) { return def_result; }
  virtual int instruction_111(t_mem code) { return def_result; }
  virtual int instruction_112(t_mem code) { return def_result; }
  virtual int instruction_113(t_mem code) { return def_result; }
  virtual int instruction_114(t_mem code) { return def_result; }
  virtual int instruction_115(t_mem code) { return def_result; }
  virtual int instruction_116(t_mem code) { return def_result; }
  virtual int instruction_117(t_mem code) { return def_result; }
  virtual int instruction_118(t_mem code) { return def_result; }
  virtual int instruction_119(t_mem code) { return def_result; }
  virtual int instruction_11a(t_mem code) { return def_result; }
  virtual int instruction_11b(t_mem code) { return def_result; }
  virtual int instruction_11c(t_mem code) { return def_result; }
  virtual int instruction_11d(t_mem code) { return def_result; }
  virtual int instruction_11e(t_mem code) { return def_result; }
  virtual int instruction_11f(t_mem code) { return def_result; }
  virtual int instruction_120(t_mem code) { return def_result; }
  virtual int instruction_121(t_mem code) { return def_result; }
  virtual int instruction_122(t_mem code) { return def_result; }
  virtual int instruction_123(t_mem code) { return def_result; }
  virtual int instruction_124(t_mem code) { return def_result; }
  virtual int instruction_125(t_mem code) { return def_result; }
  virtual int instruction_126(t_mem code) { return def_result; }
  virtual int instruction_127(t_mem code) { return def_result; }
  virtual int instruction_128(t_mem code) { return def_result; }
  virtual int instruction_129(t_mem code) { return def_result; }
  virtual int instruction_12a(t_mem code) { return def_result; }
  virtual int instruction_12b(t_mem code) { return def_result; }
  virtual int instruction_12c(t_mem code) { return def_result; }
  virtual int instruction_12d(t_mem code) { return def_result; }
  virtual int instruction_12e(t_mem code) { return def_result; }
  virtual int instruction_12f(t_mem code) { return def_result; }
  virtual int instruction_130(t_mem code) { return def_result; }
  virtual int instruction_131(t_mem code) { return def_result; }
  virtual int instruction_132(t_mem code) { return def_result; }
  virtual int instruction_133(t_mem code) { return def_result; }
  virtual int instruction_134(t_mem code) { return def_result; }
  virtual int instruction_135(t_mem code) { return def_result; }
  virtual int instruction_136(t_mem code) { return def_result; }
  virtual int instruction_137(t_mem code) { return def_result; }
  virtual int instruction_138(t_mem code) { return def_result; }
  virtual int instruction_139(t_mem code) { return def_result; }
  virtual int instruction_13a(t_mem code) { return def_result; }
  virtual int instruction_13b(t_mem code) { return def_result; }
  virtual int instruction_13c(t_mem code) { return def_result; }
  virtual int instruction_13d(t_mem code) { return def_result; }
  virtual int instruction_13e(t_mem code) { return def_result; }
  virtual int instruction_13f(t_mem code) { return def_result; }
  virtual int instruction_140(t_mem code) { return def_result; }
  virtual int instruction_141(t_mem code) { return def_result; }
  virtual int instruction_142(t_mem code) { return def_result; }
  virtual int instruction_143(t_mem code) { return def_result; }
  virtual int instruction_144(t_mem code) { return def_result; }
  virtual int instruction_145(t_mem code) { return def_result; }
  virtual int instruction_146(t_mem code) { return def_result; }
  virtual int instruction_147(t_mem code) { return def_result; }
  virtual int instruction_148(t_mem code) { return def_result; }
  virtual int instruction_149(t_mem code) { return def_result; }
  virtual int instruction_14a(t_mem code) { return def_result; }
  virtual int instruction_14b(t_mem code) { return def_result; }
  virtual int instruction_14c(t_mem code) { return def_result; }
  virtual int instruction_14d(t_mem code) { return def_result; }
  virtual int instruction_14e(t_mem code) { return def_result; }
  virtual int instruction_14f(t_mem code) { return def_result; }
  virtual int instruction_150(t_mem code) { return def_result; }
  virtual int instruction_151(t_mem code) { return def_result; }
  virtual int instruction_152(t_mem code) { return def_result; }
  virtual int instruction_153(t_mem code) { return def_result; }
  virtual int instruction_154(t_mem code) { return def_result; }
  virtual int instruction_155(t_mem code) { return def_result; }
  virtual int instruction_156(t_mem code) { return def_result; }
  virtual int instruction_157(t_mem code) { return def_result; }
  virtual int instruction_158(t_mem code) { return def_result; }
  virtual int instruction_159(t_mem code) { return def_result; }
  virtual int instruction_15a(t_mem code) { return def_result; }
  virtual int instruction_15b(t_mem code) { return def_result; }
  virtual int instruction_15c(t_mem code) { return def_result; }
  virtual int instruction_15d(t_mem code) { return def_result; }
  virtual int instruction_15e(t_mem code) { return def_result; }
  virtual int instruction_15f(t_mem code) { return def_result; }
  virtual int instruction_160(t_mem code) { return def_result; }
  virtual int instruction_161(t_mem code) { return def_result; }
  virtual int instruction_162(t_mem code) { return def_result; }
  virtual int instruction_163(t_mem code) { return def_result; }
  virtual int instruction_164(t_mem code) { return def_result; }
  virtual int instruction_165(t_mem code) { return def_result; }
  virtual int instruction_166(t_mem code) { return def_result; }
  virtual int instruction_167(t_mem code) { return def_result; }
  virtual int instruction_168(t_mem code) { return def_result; }
  virtual int instruction_169(t_mem code) { return def_result; }
  virtual int instruction_16a(t_mem code) { return def_result; }
  virtual int instruction_16b(t_mem code) { return def_result; }
  virtual int instruction_16c(t_mem code) { return def_result; }
  virtual int instruction_16d(t_mem code) { return def_result; }
  virtual int instruction_16e(t_mem code) { return def_result; }
  virtual int instruction_16f(t_mem code) { return def_result; }
  virtual int instruction_170(t_mem code) { return def_result; }
  virtual int instruction_171(t_mem code) { return def_result; }
  virtual int instruction_172(t_mem code) { return def_result; }
  virtual int instruction_173(t_mem code) { return def_result; }
  virtual int instruction_174(t_mem code) { return def_result; }
  virtual int instruction_175(t_mem code) { return def_result; }
  virtual int instruction_176(t_mem code) { return def_result; }
  virtual int instruction_177(t_mem code) { return def_result; }
  virtual int instruction_178(t_mem code) { return def_result; }
  virtual int instruction_179(t_mem code) { return def_result; }
  virtual int instruction_17a(t_mem code) { return def_result; }
  virtual int instruction_17b(t_mem code) { return def_result; }
  virtual int instruction_17c(t_mem code) { return def_result; }
  virtual int instruction_17d(t_mem code) { return def_result; }
  virtual int instruction_17e(t_mem code) { return def_result; }
  virtual int instruction_17f(t_mem code) { return def_result; }
  virtual int instruction_180(t_mem code) { return def_result; }
  virtual int instruction_181(t_mem code) { return def_result; }
  virtual int instruction_182(t_mem code) { return def_result; }
  virtual int instruction_183(t_mem code) { return def_result; }
  virtual int instruction_184(t_mem code) { return def_result; }
  virtual int instruction_185(t_mem code) { return def_result; }
  virtual int instruction_186(t_mem code) { return def_result; }
  virtual int instruction_187(t_mem code) { return def_result; }
  virtual int instruction_188(t_mem code) { return def_result; }
  virtual int instruction_189(t_mem code) { return def_result; }
  virtual int instruction_18a(t_mem code) { return def_result; }
  virtual int instruction_18b(t_mem code) { return def_result; }
  virtual int instruction_18c(t_mem code) { return def_result; }
  virtual int instruction_18d(t_mem code) { return def_result; }
  virtual int instruction_18e(t_mem code) { return def_result; }
  virtual int instruction_18f(t_mem code) { return def_result; }
  virtual int instruction_190(t_mem code) { return def_result; }
  virtual int instruction_191(t_mem code) { return def_result; }
  virtual int instruction_192(t_mem code) { return def_result; }
  virtual int instruction_193(t_mem code) { return def_result; }
  virtual int instruction_194(t_mem code) { return def_result; }
  virtual int instruction_195(t_mem code) { return def_result; }
  virtual int instruction_196(t_mem code) { return def_result; }
  virtual int instruction_197(t_mem code) { return def_result; }
  virtual int instruction_198(t_mem code) { return def_result; }
  virtual int instruction_199(t_mem code) { return def_result; }
  virtual int instruction_19a(t_mem code) { return def_result; }
  virtual int instruction_19b(t_mem code) { return def_result; }
  virtual int instruction_19c(t_mem code) { return def_result; }
  virtual int instruction_19d(t_mem code) { return def_result; }
  virtual int instruction_19e(t_mem code) { return def_result; }
  virtual int instruction_19f(t_mem code) { return def_result; }
  virtual int instruction_1a0(t_mem code) { return def_result; }
  virtual int instruction_1a1(t_mem code) { return def_result; }
  virtual int instruction_1a2(t_mem code) { return def_result; }
  virtual int instruction_1a3(t_mem code) { return def_result; }
  virtual int instruction_1a4(t_mem code) { return def_result; }
  virtual int instruction_1a5(t_mem code) { return def_result; }
  virtual int instruction_1a6(t_mem code) { return def_result; }
  virtual int instruction_1a7(t_mem code) { return def_result; }
  virtual int instruction_1a8(t_mem code) { return def_result; }
  virtual int instruction_1a9(t_mem code) { return def_result; }
  virtual int instruction_1aa(t_mem code) { return def_result; }
  virtual int instruction_1ab(t_mem code) { return def_result; }
  virtual int instruction_1ac(t_mem code) { return def_result; }
  virtual int instruction_1ad(t_mem code) { return def_result; }
  virtual int instruction_1ae(t_mem code) { return def_result; }
  virtual int instruction_1af(t_mem code) { return def_result; }
  virtual int instruction_1b0(t_mem code) { return def_result; }
  virtual int instruction_1b1(t_mem code) { return def_result; }
  virtual int instruction_1b2(t_mem code) { return def_result; }
  virtual int instruction_1b3(t_mem code) { return def_result; }
  virtual int instruction_1b4(t_mem code) { return def_result; }
  virtual int instruction_1b5(t_mem code) { return def_result; }
  virtual int instruction_1b6(t_mem code) { return def_result; }
  virtual int instruction_1b7(t_mem code) { return def_result; }
  virtual int instruction_1b8(t_mem code) { return def_result; }
  virtual int instruction_1b9(t_mem code) { return def_result; }
  virtual int instruction_1ba(t_mem code) { return def_result; }
  virtual int instruction_1bb(t_mem code) { return def_result; }
  virtual int instruction_1bc(t_mem code) { return def_result; }
  virtual int instruction_1bd(t_mem code) { return def_result; }
  virtual int instruction_1be(t_mem code) { return def_result; }
  virtual int instruction_1bf(t_mem code) { return def_result; }
  virtual int instruction_1c0(t_mem code) { return def_result; }
  virtual int instruction_1c1(t_mem code) { return def_result; }
  virtual int instruction_1c2(t_mem code) { return def_result; }
  virtual int instruction_1c3(t_mem code) { return def_result; }
  virtual int instruction_1c4(t_mem code) { return def_result; }
  virtual int instruction_1c5(t_mem code) { return def_result; }
  virtual int instruction_1c6(t_mem code) { return def_result; }
  virtual int instruction_1c7(t_mem code) { return def_result; }
  virtual int instruction_1c8(t_mem code) { return def_result; }
  virtual int instruction_1c9(t_mem code) { return def_result; }
  virtual int instruction_1ca(t_mem code) { return def_result; }
  virtual int instruction_1cb(t_mem code) { return def_result; }
  virtual int instruction_1cc(t_mem code) { return def_result; }
  virtual int instruction_1cd(t_mem code) { return def_result; }
  virtual int instruction_1ce(t_mem code) { return def_result; }
  virtual int instruction_1cf(t_mem code) { return def_result; }
  virtual int instruction_1d0(t_mem code) { return def_result; }
  virtual int instruction_1d1(t_mem code) { return def_result; }
  virtual int instruction_1d2(t_mem code) { return def_result; }
  virtual int instruction_1d3(t_mem code) { return def_result; }
  virtual int instruction_1d4(t_mem code) { return def_result; }
  virtual int instruction_1d5(t_mem code) { return def_result; }
  virtual int instruction_1d6(t_mem code) { return def_result; }
  virtual int instruction_1d7(t_mem code) { return def_result; }
  virtual int instruction_1d8(t_mem code) { return def_result; }
  virtual int instruction_1d9(t_mem code) { return def_result; }
  virtual int instruction_1da(t_mem code) { return def_result; }
  virtual int instruction_1db(t_mem code) { return def_result; }
  virtual int instruction_1dc(t_mem code) { return def_result; }
  virtual int instruction_1dd(t_mem code) { return def_result; }
  virtual int instruction_1de(t_mem code) { return def_result; }
  virtual int instruction_1df(t_mem code) { return def_result; }
  virtual int instruction_1e0(t_mem code) { return def_result; }
  virtual int instruction_1e1(t_mem code) { return def_result; }
  virtual int instruction_1e2(t_mem code) { return def_result; }
  virtual int instruction_1e3(t_mem code) { return def_result; }
  virtual int instruction_1e4(t_mem code) { return def_result; }
  virtual int instruction_1e5(t_mem code) { return def_result; }
  virtual int instruction_1e6(t_mem code) { return def_result; }
  virtual int instruction_1e7(t_mem code) { return def_result; }
  virtual int instruction_1e8(t_mem code) { return def_result; }
  virtual int instruction_1e9(t_mem code) { return def_result; }
  virtual int instruction_1ea(t_mem code) { return def_result; }
  virtual int instruction_1eb(t_mem code) { return def_result; }
  virtual int instruction_1ec(t_mem code) { return def_result; }
  virtual int instruction_1ed(t_mem code) { return def_result; }
  virtual int instruction_1ee(t_mem code) { return def_result; }
  virtual int instruction_1ef(t_mem code) { return def_result; }
  virtual int instruction_1f0(t_mem code) { return def_result; }
  virtual int instruction_1f1(t_mem code) { return def_result; }
  virtual int instruction_1f2(t_mem code) { return def_result; }
  virtual int instruction_1f3(t_mem code) { return def_result; }
  virtual int instruction_1f4(t_mem code) { return def_result; }
  virtual int instruction_1f5(t_mem code) { return def_result; }
  virtual int instruction_1f6(t_mem code) { return def_result; }
  virtual int instruction_1f7(t_mem code) { return def_result; }
  virtual int instruction_1f8(t_mem code) { return def_result; }
  virtual int instruction_1f9(t_mem code) { return def_result; }
  virtual int instruction_1fa(t_mem code) { return def_result; }
  virtual int instruction_1fb(t_mem code) { return def_result; }
  virtual int instruction_1fc(t_mem code) { return def_result; }
  virtual int instruction_1fd(t_mem code) { return def_result; }
  virtual int instruction_1fe(t_mem code) { return def_result; }
  virtual int instruction_1ff(t_mem code) { return def_result; }
  
  virtual int instruction_200(t_mem code) { return def_result; }
  virtual int instruction_201(t_mem code) { return def_result; }
  virtual int instruction_202(t_mem code) { return def_result; }
  virtual int instruction_203(t_mem code) { return def_result; }
  virtual int instruction_204(t_mem code) { return def_result; }
  virtual int instruction_205(t_mem code) { return def_result; }
  virtual int instruction_206(t_mem code) { return def_result; }
  virtual int instruction_207(t_mem code) { return def_result; }
  virtual int instruction_208(t_mem code) { return def_result; }
  virtual int instruction_209(t_mem code) { return def_result; }
  virtual int instruction_20a(t_mem code) { return def_result; }
  virtual int instruction_20b(t_mem code) { return def_result; }
  virtual int instruction_20c(t_mem code) { return def_result; }
  virtual int instruction_20d(t_mem code) { return def_result; }
  virtual int instruction_20e(t_mem code) { return def_result; }
  virtual int instruction_20f(t_mem code) { return def_result; }
  virtual int instruction_210(t_mem code) { return def_result; }
  virtual int instruction_211(t_mem code) { return def_result; }
  virtual int instruction_212(t_mem code) { return def_result; }
  virtual int instruction_213(t_mem code) { return def_result; }
  virtual int instruction_214(t_mem code) { return def_result; }
  virtual int instruction_215(t_mem code) { return def_result; }
  virtual int instruction_216(t_mem code) { return def_result; }
  virtual int instruction_217(t_mem code) { return def_result; }
  virtual int instruction_218(t_mem code) { return def_result; }
  virtual int instruction_219(t_mem code) { return def_result; }
  virtual int instruction_21a(t_mem code) { return def_result; }
  virtual int instruction_21b(t_mem code) { return def_result; }
  virtual int instruction_21c(t_mem code) { return def_result; }
  virtual int instruction_21d(t_mem code) { return def_result; }
  virtual int instruction_21e(t_mem code) { return def_result; }
  virtual int instruction_21f(t_mem code) { return def_result; }
  virtual int instruction_220(t_mem code) { return def_result; }
  virtual int instruction_221(t_mem code) { return def_result; }
  virtual int instruction_222(t_mem code) { return def_result; }
  virtual int instruction_223(t_mem code) { return def_result; }
  virtual int instruction_224(t_mem code) { return def_result; }
  virtual int instruction_225(t_mem code) { return def_result; }
  virtual int instruction_226(t_mem code) { return def_result; }
  virtual int instruction_227(t_mem code) { return def_result; }
  virtual int instruction_228(t_mem code) { return def_result; }
  virtual int instruction_229(t_mem code) { return def_result; }
  virtual int instruction_22a(t_mem code) { return def_result; }
  virtual int instruction_22b(t_mem code) { return def_result; }
  virtual int instruction_22c(t_mem code) { return def_result; }
  virtual int instruction_22d(t_mem code) { return def_result; }
  virtual int instruction_22e(t_mem code) { return def_result; }
  virtual int instruction_22f(t_mem code) { return def_result; }
  virtual int instruction_230(t_mem code) { return def_result; }
  virtual int instruction_231(t_mem code) { return def_result; }
  virtual int instruction_232(t_mem code) { return def_result; }
  virtual int instruction_233(t_mem code) { return def_result; }
  virtual int instruction_234(t_mem code) { return def_result; }
  virtual int instruction_235(t_mem code) { return def_result; }
  virtual int instruction_236(t_mem code) { return def_result; }
  virtual int instruction_237(t_mem code) { return def_result; }
  virtual int instruction_238(t_mem code) { return def_result; }
  virtual int instruction_239(t_mem code) { return def_result; }
  virtual int instruction_23a(t_mem code) { return def_result; }
  virtual int instruction_23b(t_mem code) { return def_result; }
  virtual int instruction_23c(t_mem code) { return def_result; }
  virtual int instruction_23d(t_mem code) { return def_result; }
  virtual int instruction_23e(t_mem code) { return def_result; }
  virtual int instruction_23f(t_mem code) { return def_result; }
  virtual int instruction_240(t_mem code) { return def_result; }
  virtual int instruction_241(t_mem code) { return def_result; }
  virtual int instruction_242(t_mem code) { return def_result; }
  virtual int instruction_243(t_mem code) { return def_result; }
  virtual int instruction_244(t_mem code) { return def_result; }
  virtual int instruction_245(t_mem code) { return def_result; }
  virtual int instruction_246(t_mem code) { return def_result; }
  virtual int instruction_247(t_mem code) { return def_result; }
  virtual int instruction_248(t_mem code) { return def_result; }
  virtual int instruction_249(t_mem code) { return def_result; }
  virtual int instruction_24a(t_mem code) { return def_result; }
  virtual int instruction_24b(t_mem code) { return def_result; }
  virtual int instruction_24c(t_mem code) { return def_result; }
  virtual int instruction_24d(t_mem code) { return def_result; }
  virtual int instruction_24e(t_mem code) { return def_result; }
  virtual int instruction_24f(t_mem code) { return def_result; }
  virtual int instruction_250(t_mem code) { return def_result; }
  virtual int instruction_251(t_mem code) { return def_result; }
  virtual int instruction_252(t_mem code) { return def_result; }
  virtual int instruction_253(t_mem code) { return def_result; }
  virtual int instruction_254(t_mem code) { return def_result; }
  virtual int instruction_255(t_mem code) { return def_result; }
  virtual int instruction_256(t_mem code) { return def_result; }
  virtual int instruction_257(t_mem code) { return def_result; }
  virtual int instruction_258(t_mem code) { return def_result; }
  virtual int instruction_259(t_mem code) { return def_result; }
  virtual int instruction_25a(t_mem code) { return def_result; }
  virtual int instruction_25b(t_mem code) { return def_result; }
  virtual int instruction_25c(t_mem code) { return def_result; }
  virtual int instruction_25d(t_mem code) { return def_result; }
  virtual int instruction_25e(t_mem code) { return def_result; }
  virtual int instruction_25f(t_mem code) { return def_result; }
  virtual int instruction_260(t_mem code) { return def_result; }
  virtual int instruction_261(t_mem code) { return def_result; }
  virtual int instruction_262(t_mem code) { return def_result; }
  virtual int instruction_263(t_mem code) { return def_result; }
  virtual int instruction_264(t_mem code) { return def_result; }
  virtual int instruction_265(t_mem code) { return def_result; }
  virtual int instruction_266(t_mem code) { return def_result; }
  virtual int instruction_267(t_mem code) { return def_result; }
  virtual int instruction_268(t_mem code) { return def_result; }
  virtual int instruction_269(t_mem code) { return def_result; }
  virtual int instruction_26a(t_mem code) { return def_result; }
  virtual int instruction_26b(t_mem code) { return def_result; }
  virtual int instruction_26c(t_mem code) { return def_result; }
  virtual int instruction_26d(t_mem code) { return def_result; }
  virtual int instruction_26e(t_mem code) { return def_result; }
  virtual int instruction_26f(t_mem code) { return def_result; }
  virtual int instruction_270(t_mem code) { return def_result; }
  virtual int instruction_271(t_mem code) { return def_result; }
  virtual int instruction_272(t_mem code) { return def_result; }
  virtual int instruction_273(t_mem code) { return def_result; }
  virtual int instruction_274(t_mem code) { return def_result; }
  virtual int instruction_275(t_mem code) { return def_result; }
  virtual int instruction_276(t_mem code) { return def_result; }
  virtual int instruction_277(t_mem code) { return def_result; }
  virtual int instruction_278(t_mem code) { return def_result; }
  virtual int instruction_279(t_mem code) { return def_result; }
  virtual int instruction_27a(t_mem code) { return def_result; }
  virtual int instruction_27b(t_mem code) { return def_result; }
  virtual int instruction_27c(t_mem code) { return def_result; }
  virtual int instruction_27d(t_mem code) { return def_result; }
  virtual int instruction_27e(t_mem code) { return def_result; }
  virtual int instruction_27f(t_mem code) { return def_result; }
  virtual int instruction_280(t_mem code) { return def_result; }
  virtual int instruction_281(t_mem code) { return def_result; }
  virtual int instruction_282(t_mem code) { return def_result; }
  virtual int instruction_283(t_mem code) { return def_result; }
  virtual int instruction_284(t_mem code) { return def_result; }
  virtual int instruction_285(t_mem code) { return def_result; }
  virtual int instruction_286(t_mem code) { return def_result; }
  virtual int instruction_287(t_mem code) { return def_result; }
  virtual int instruction_288(t_mem code) { return def_result; }
  virtual int instruction_289(t_mem code) { return def_result; }
  virtual int instruction_28a(t_mem code) { return def_result; }
  virtual int instruction_28b(t_mem code) { return def_result; }
  virtual int instruction_28c(t_mem code) { return def_result; }
  virtual int instruction_28d(t_mem code) { return def_result; }
  virtual int instruction_28e(t_mem code) { return def_result; }
  virtual int instruction_28f(t_mem code) { return def_result; }
  virtual int instruction_290(t_mem code) { return def_result; }
  virtual int instruction_291(t_mem code) { return def_result; }
  virtual int instruction_292(t_mem code) { return def_result; }
  virtual int instruction_293(t_mem code) { return def_result; }
  virtual int instruction_294(t_mem code) { return def_result; }
  virtual int instruction_295(t_mem code) { return def_result; }
  virtual int instruction_296(t_mem code) { return def_result; }
  virtual int instruction_297(t_mem code) { return def_result; }
  virtual int instruction_298(t_mem code) { return def_result; }
  virtual int instruction_299(t_mem code) { return def_result; }
  virtual int instruction_29a(t_mem code) { return def_result; }
  virtual int instruction_29b(t_mem code) { return def_result; }
  virtual int instruction_29c(t_mem code) { return def_result; }
  virtual int instruction_29d(t_mem code) { return def_result; }
  virtual int instruction_29e(t_mem code) { return def_result; }
  virtual int instruction_29f(t_mem code) { return def_result; }
  virtual int instruction_2a0(t_mem code) { return def_result; }
  virtual int instruction_2a1(t_mem code) { return def_result; }
  virtual int instruction_2a2(t_mem code) { return def_result; }
  virtual int instruction_2a3(t_mem code) { return def_result; }
  virtual int instruction_2a4(t_mem code) { return def_result; }
  virtual int instruction_2a5(t_mem code) { return def_result; }
  virtual int instruction_2a6(t_mem code) { return def_result; }
  virtual int instruction_2a7(t_mem code) { return def_result; }
  virtual int instruction_2a8(t_mem code) { return def_result; }
  virtual int instruction_2a9(t_mem code) { return def_result; }
  virtual int instruction_2aa(t_mem code) { return def_result; }
  virtual int instruction_2ab(t_mem code) { return def_result; }
  virtual int instruction_2ac(t_mem code) { return def_result; }
  virtual int instruction_2ad(t_mem code) { return def_result; }
  virtual int instruction_2ae(t_mem code) { return def_result; }
  virtual int instruction_2af(t_mem code) { return def_result; }
  virtual int instruction_2b0(t_mem code) { return def_result; }
  virtual int instruction_2b1(t_mem code) { return def_result; }
  virtual int instruction_2b2(t_mem code) { return def_result; }
  virtual int instruction_2b3(t_mem code) { return def_result; }
  virtual int instruction_2b4(t_mem code) { return def_result; }
  virtual int instruction_2b5(t_mem code) { return def_result; }
  virtual int instruction_2b6(t_mem code) { return def_result; }
  virtual int instruction_2b7(t_mem code) { return def_result; }
  virtual int instruction_2b8(t_mem code) { return def_result; }
  virtual int instruction_2b9(t_mem code) { return def_result; }
  virtual int instruction_2ba(t_mem code) { return def_result; }
  virtual int instruction_2bb(t_mem code) { return def_result; }
  virtual int instruction_2bc(t_mem code) { return def_result; }
  virtual int instruction_2bd(t_mem code) { return def_result; }
  virtual int instruction_2be(t_mem code) { return def_result; }
  virtual int instruction_2bf(t_mem code) { return def_result; }
  virtual int instruction_2c0(t_mem code) { return def_result; }
  virtual int instruction_2c1(t_mem code) { return def_result; }
  virtual int instruction_2c2(t_mem code) { return def_result; }
  virtual int instruction_2c3(t_mem code) { return def_result; }
  virtual int instruction_2c4(t_mem code) { return def_result; }
  virtual int instruction_2c5(t_mem code) { return def_result; }
  virtual int instruction_2c6(t_mem code) { return def_result; }
  virtual int instruction_2c7(t_mem code) { return def_result; }
  virtual int instruction_2c8(t_mem code) { return def_result; }
  virtual int instruction_2c9(t_mem code) { return def_result; }
  virtual int instruction_2ca(t_mem code) { return def_result; }
  virtual int instruction_2cb(t_mem code) { return def_result; }
  virtual int instruction_2cc(t_mem code) { return def_result; }
  virtual int instruction_2cd(t_mem code) { return def_result; }
  virtual int instruction_2ce(t_mem code) { return def_result; }
  virtual int instruction_2cf(t_mem code) { return def_result; }
  virtual int instruction_2d0(t_mem code) { return def_result; }
  virtual int instruction_2d1(t_mem code) { return def_result; }
  virtual int instruction_2d2(t_mem code) { return def_result; }
  virtual int instruction_2d3(t_mem code) { return def_result; }
  virtual int instruction_2d4(t_mem code) { return def_result; }
  virtual int instruction_2d5(t_mem code) { return def_result; }
  virtual int instruction_2d6(t_mem code) { return def_result; }
  virtual int instruction_2d7(t_mem code) { return def_result; }
  virtual int instruction_2d8(t_mem code) { return def_result; }
  virtual int instruction_2d9(t_mem code) { return def_result; }
  virtual int instruction_2da(t_mem code) { return def_result; }
  virtual int instruction_2db(t_mem code) { return def_result; }
  virtual int instruction_2dc(t_mem code) { return def_result; }
  virtual int instruction_2dd(t_mem code) { return def_result; }
  virtual int instruction_2de(t_mem code) { return def_result; }
  virtual int instruction_2df(t_mem code) { return def_result; }
  virtual int instruction_2e0(t_mem code) { return def_result; }
  virtual int instruction_2e1(t_mem code) { return def_result; }
  virtual int instruction_2e2(t_mem code) { return def_result; }
  virtual int instruction_2e3(t_mem code) { return def_result; }
  virtual int instruction_2e4(t_mem code) { return def_result; }
  virtual int instruction_2e5(t_mem code) { return def_result; }
  virtual int instruction_2e6(t_mem code) { return def_result; }
  virtual int instruction_2e7(t_mem code) { return def_result; }
  virtual int instruction_2e8(t_mem code) { return def_result; }
  virtual int instruction_2e9(t_mem code) { return def_result; }
  virtual int instruction_2ea(t_mem code) { return def_result; }
  virtual int instruction_2eb(t_mem code) { return def_result; }
  virtual int instruction_2ec(t_mem code) { return def_result; }
  virtual int instruction_2ed(t_mem code) { return def_result; }
  virtual int instruction_2ee(t_mem code) { return def_result; }
  virtual int instruction_2ef(t_mem code) { return def_result; }
  virtual int instruction_2f0(t_mem code) { return def_result; }
  virtual int instruction_2f1(t_mem code) { return def_result; }
  virtual int instruction_2f2(t_mem code) { return def_result; }
  virtual int instruction_2f3(t_mem code) { return def_result; }
  virtual int instruction_2f4(t_mem code) { return def_result; }
  virtual int instruction_2f5(t_mem code) { return def_result; }
  virtual int instruction_2f6(t_mem code) { return def_result; }
  virtual int instruction_2f7(t_mem code) { return def_result; }
  virtual int instruction_2f8(t_mem code) { return def_result; }
  virtual int instruction_2f9(t_mem code) { return def_result; }
  virtual int instruction_2fa(t_mem code) { return def_result; }
  virtual int instruction_2fb(t_mem code) { return def_result; }
  virtual int instruction_2fc(t_mem code) { return def_result; }
  virtual int instruction_2fd(t_mem code) { return def_result; }
  virtual int instruction_2fe(t_mem code) { return def_result; }
  virtual int instruction_2ff(t_mem code) { return def_result; }
};


#endif

/* End of sim.src/itabcl.h */
