virtual int instruction_6k11_43(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k11_44(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k11_4b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k11_53(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k11_80(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k11_88(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k11_90(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k6d_0d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_0f(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_1d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_1f(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_4d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_4f(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_5d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_5f(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_8d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_8f(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_9d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_9f(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_cd(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_cf(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_dd(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k6d_df(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k7f_43(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k7f_44(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k7f_4b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k7f_53(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k7f_59(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k7f_69(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k7f_80(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k7f_88(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k7f_90(t_mem code) { return resNOT_DONE; }

virtual int instruction_6kcb_30(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kcb_31(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kcb_32(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kcb_33(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kcb_34(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kcb_35(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kcb_37(t_mem code) { return resNOT_DONE; }

virtual int instruction_6kdd_32(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_80(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_81(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_82(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_83(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_90(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_91(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_92(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_93(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_a0(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_a1(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_a2(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_a3(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_b0(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_b1(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_b2(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_b3(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kdd_c5(t_mem code) { return resNOT_DONE; }

virtual int instruction_6ked_5c(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_86(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_87(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_8e(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_8f(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_96(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_97(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_9a(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_9b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_9c(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_9e(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_9f(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_a6(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_a7(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_ae(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_af(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_b6(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_b7(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_be(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_bf(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_c7(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_ce(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_cf(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_d7(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_de(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_df(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_e2(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_e3(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_e4(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_ef(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_f2(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_f3(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_f4(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_f7(t_mem code) { return resNOT_DONE; }
virtual int instruction_6ked_ff(t_mem code) { return resNOT_DONE; }

virtual int instruction_6kfd_32(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_80(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_81(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_82(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_83(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_90(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_91(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_92(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_93(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_a0(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_a1(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_a2(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_a3(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_b0(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_b1(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_b2(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_b3(t_mem code) { return resNOT_DONE; }
virtual int instruction_6kfd_c5(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_00(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_01(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_02(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_03(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_04(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_05(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_06(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_07(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_08(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_09(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_0a(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_0b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_0c(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_0d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_0e(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_0f(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_10(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_11(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_12(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_13(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_14(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_15(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_16(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_17(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_18(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_19(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_1a(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_1b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_1c(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_1d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_1e(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_1f(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_20(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_21(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_22(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_23(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_24(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_25(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_26(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_27(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_28(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_29(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_2a(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_2b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_2c(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_2d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_2e(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_2f(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_30(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_31(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_32(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_33(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_34(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_35(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_36(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_37(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_38(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_39(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_3a(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_3b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_3c(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_3d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_3e(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_3f(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_40(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_41(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_42(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_43(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_44(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_45(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_46(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_47(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_48(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_49(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_4a(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_4b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_4c(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_4d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_4e(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_4f(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_50(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_51(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_52(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_53(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_54(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_55(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_56(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_57(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_58(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_59(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_5a(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_5b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_5c(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_5d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_5e(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_5f(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_60(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_61(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_62(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_63(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_64(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_65(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_66(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_67(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_68(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_69(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_6a(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_6b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_6c(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_6d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_6e(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_6f(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_70(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_71(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_72(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_73(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_74(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_75(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_76(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_77(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_78(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_79(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_7a(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_7b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_7c(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_7d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_7e(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_7f(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_89(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_8a(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_8b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_8c(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_8d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_8e(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_8f(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_90(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_98(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_99(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_9a(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_9b(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_9c(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_9d(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_9e(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_9f(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_a0(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_a2(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_a3(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_a4(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_a5(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_a6(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_a7(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_a8(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_a9(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_aa(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ab(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ac(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ad(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ae(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_af(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_b0(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_b2(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_b3(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_b4(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_b5(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_b6(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_b7(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_b8(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_b9(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ba(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_bb(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_bc(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_bd(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_be(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_bf(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_c0(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_c2(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_c3(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_c8(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_c9(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ca(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_cb(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_cc(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_cd(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ce(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_cf(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_d0(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_d2(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_d3(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_d8(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_d9(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_da(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_db(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_dc(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_dd(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_de(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_df(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_e2(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_e3(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_e9(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ea(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_eb(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ec(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ed(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ee(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ef(t_mem code) { return resNOT_DONE; }

virtual int instruction_6k49_f0(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_f8(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_f9(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_fa(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_fb(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_fc(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_fd(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_fe(t_mem code) { return resNOT_DONE; }
virtual int instruction_6k49_ff(t_mem code) { return resNOT_DONE; }
