#include "appmake/zx_reference.h"

#include <array>
#include <format>

namespace appmake {

namespace {

constexpr std::array<rom_routine_info, 300> k_rom_routines = {{
    {0x0000, "THE 'START'"},
    {0x0008, "THE 'ERROR' RESTART"},
    {0x0010, "THE 'PRINT A CHARACTER' RESTART"},
    {0x0018, "THE 'COLLECT CHARACTER' RESTART"},
    {0x0020, "THE 'COLLECT NEXT CHARACTER' RESTART"},
    {0x0028, "THE 'CALCULATOR' RESTART"},
    {0x0030, "THE 'MAKE BC SPACES' RESTART"},
    {0x0038, "THE 'MASKABLE INTERRUPT' ROUTINE"},
    {0x0053, "THE 'ERROR-2' ROUTINE"},
    {0x0074, "THE 'CH-ADD+1' SUBROUTINE"},
    {0x007d, "THE 'SKIP-OVER' SUBROUTINE"},
    {0x028e, "THE 'KEYBOARD SCANNING' SUBROUTINE"},
    {0x02bf, "THE 'KEYBOARD' SUBROUTINE"},
    {0x031e, "THE 'K-TEST' SUBROUTINE"},
    {0x0333, "THE 'KEYBOARD DECODING' SUBROUTINE"},
    {0x03b5, "THE 'BEEPER' SUBROUTINE"},
    {0x03f8, "THE 'BEEP' COMMAND ROUTINE"},
    {0x04c2, "THE 'SA-BYTES' SUBROUTINE"},
    {0x053f, "THE 'SA/LD-RET' SUBROUTINE"},
    {0x0556, "THE 'LD-BYTES' SUBROUTINE"},
    {0x05e3, "THE 'LD-EDGE-2' AND 'LD-EDGE-1' SUBROUTINES"},
    {0x0605, "THE 'SAVE, LOAD, VERIFY and MERGE' COMMAND ROUTINES"},
    {0x07cb, "THE 'VERIFY' CONTROL ROUTINE"},
    {0x0802, "THE 'LOAD A DATA BLOCK' SUBROUTINE"},
    {0x0808, "THE 'LOAD' CONTROL ROUTINE"},
    {0x08b6, "THE 'MERGE' CONTROL ROUTINE"},
    {0x092c, "THE 'MERGE A LINE OR A VARIABLE' SUBROUTINE"},
    {0x0970, "THE 'SAVE' CONTROL ROUTINE"},
    {0x09f4, "THE 'PRINT-OUT' ROUTINES"},
    {0x0a23, "THE 'CURSOR LEFT' SUBROUTINE"},
    {0x0a3d, "THE 'CURSOR RIGHT' SUBROUTINE"},
    {0x0a4f, "THE 'CARRIAGE RETURN' SUBROUTINE"},
    {0x0a5f, "THE 'PRINT COMMA' SUBROUTINE"},
    {0x0a69, "THE 'PRINT A QUESTION MARK' SUBROUTINE"},
    {0x0a6d, "THE 'CONTROL CHARACTERS WITH OPERANDS' ROUTINE"},
    {0x0ad9, "THE 'POSITION STORE' SUBROUTINE"},
    {0x0b03, "THE 'POSITION FETCH' SUBROUTINE"},
    {0x0b24, "THE 'PRINT ANY CHARACTER(S)' SUBROUTINE"},
    {0x0bdb, "THE 'SET ATTRIBUTE BYTE' SUBROUTINE"},
    {0x0c0a, "THE 'MESSAGE PRINTING' SUBROUTINE"},
    {0x0c3b, "THE 'PO-SAVE' SUBROUTINE"},
    {0x0c41, "THE 'TABLE SEARCH' SUBROUTINE"},
    {0x0c55, "THE 'TEST FOR SCROLL' SUBROUTINE"},
    {0x0d4d, "THE 'TEMPORARY COLOUR ITEMS' SUBROUTINE"},
    {0x0d6b, "THE 'CLS' COMMAND ROUTINE"},
    {0x0daf, "THE 'CLEARING THE WHOLE DISPLAY AREA' SUBROUTINE"},
    {0x0dd9, "THE 'CL-SET' SUBROUTINE"},
    {0x0dfe, "THE 'SCROLLING' SUBROUTINE"},
    {0x0e44, "THE 'CLEAR LINES' SUBROUTINE"},
    {0x0e88, "THE 'CL-ATTR' SUBROUTINE"},
    {0x0e9b, "THE 'CL-ADDR' SUBROUTINE"},
    {0x0eac, "THE 'COPY' COMMAND ROUTINE"},
    {0x0ecd, "THE 'COPY-BUFF' SUBROUTINE"},
    {0x0edf, "THE 'CLEAR PRINTER BUFFER' SUBROUTINE"},
    {0x0ef4, "THE 'COPY-LINE' SUBROUTINE"},
    {0x0f2c, "THE 'EDITOR' ROUTINES"},
    {0x0fa9, "THE 'EDIT KEY' SUBROUTINE"},
    {0x0ff3, "THE 'CURSOR DOWN EDITING' SUBROUTINE"},
    {0x1007, "THE 'CURSOR LEFT EDITING' SUBROUTINE"},
    {0x100c, "THE 'CURSOR RIGHT EDITING' SUBROUTINE"},
    {0x1015, "THE 'DELETE EDITING' SUBROUTINE"},
    {0x101e, "THE 'ED-IGNORE' SUBROUTINE"},
    {0x1024, "THE 'ENTER EDITING' SUBROUTINE"},
    {0x1031, "THE 'ED-EDGE' SUBROUTINE"},
    {0x1059, "THE 'CURSOR UP EDITING' SUBROUTINE"},
    {0x1076, "THE 'ED-SYMBOL' SUBROUTINE"},
    {0x107f, "THE 'ED-ERROR' SUBROUTINE"},
    {0x1097, "THE 'CLEAR-SP' SUBROUTINE"},
    {0x10a8, "THE 'KEYBOARD INPUT' SUBROUTINE"},
    {0x111d, "THE 'LOWER SCREEN COPYING' SUBROUTINE"},
    {0x1190, "THE 'SET-HL' AND 'SET-DE' SUBROUTINES"},
    {0x11a7, "THE 'REMOVE-FP' SUBROUTINE"},
    {0x11b7, "THE 'NEW' COMMAND ROUTINE"},
    {0x12a2, "THE 'MAIN EXECUTION' LOOP"},
    {0x1555, "THE 'MAIN-ADD' SUBROUTINE"},
    {0x15c4, "THE 'WAIT-KEY' SUBROUTINE"},
    {0x15e6, "THE 'INPUT-AD' SUBROUTINE"},
    {0x15ef, "THE 'MAIN PRINTING' SUBROUTINE"},
    {0x1601, "THE 'CHAN-OPEN' SUBROUTINE"},
    {0x1615, "THE 'CHAN-FLAG' SUBROUTINE"},
    {0x1634, "THE 'CHANNEL 'K' FLAG' SUBROUTINE"},
    {0x1642, "THE 'CHANNEL 'S' FLAG' SUBROUTINE"},
    {0x164d, "THE 'CHANNEL 'P' FLAG' SUBROUTINE"},
    {0x1652, "THE 'MAKE-ROOM' SUBROUTINE"},
    {0x1664, "THE 'POINTERS' SUBROUTINE"},
    {0x168f, "THE 'COLLECT A LINE NUMBER' SUBROUTINE"},
    {0x169e, "THE 'RESERVE' SUBROUTINE"},
    {0x16b0, "THE 'SET-MIN' SUBROUTINE"},
    {0x16db, "THE 'INDEXER' SUBROUTINE"},
    {0x16e5, "THE 'CLOSE #' COMMAND ROUTINE"},
    {0x1701, "THE 'CLOSE-2' SUBROUTINE"},
    {0x171c, "THE 'CLOSE STREAM' SUBROUTINE"},
    {0x171e, "THE 'STREAM DATA' SUBROUTINE"},
    {0x1736, "THE 'OPEN #' COMMAND ROUTINE"},
    {0x175d, "THE 'OPEN-2' SUBROUTINE"},
    {0x1781, "THE 'OPEN-K' SUBROUTINE"},
    {0x1785, "THE 'OPEN-S' SUBROUTINE"},
    {0x1789, "THE 'OPEN-P' SUBROUTINE"},
    {0x1793, "THE 'CAT, ERASE, FORMAT and MOVE' COMMAND ROUTINES"},
    {0x1795, "THE 'LIST and LLIST' COMMAND ROUTINES"},
    {0x17f5, "THE 'LLIST' ENTRY POINT"},
    {0x17f9, "THE 'LIST' ENTRY POINT"},
    {0x1855, "THE 'PRINT A WHOLE BASIC LINE' SUBROUTINE"},
    {0x18b6, "THE 'NUMBER' SUBROUTINE"},
    {0x18c1, "THE 'PRINT A FLASHING CHARACTER' SUBROUTINE"},
    {0x18e1, "THE 'PRINT THE CURSOR' SUBROUTINE"},
    {0x190f, "THE 'LN-FETCH' SUBROUTINE"},
    {0x1925, "THE 'PRINTING CHARACTERS IN A BASIC LINE' SUBROUTINE"},
    {0x196e, "THE 'LINE-ADDR' SUBROUTINE"},
    {0x1980, "THE 'COMPARE LINE NUMBERS' SUBROUTINE"},
    {0x198b, "THE 'FIND EACH STATEMENT' SUBROUTINE"},
    {0x19b8, "THE 'NEXT-ONE' SUBROUTINE"},
    {0x19dd, "THE 'DIFFERENCE' SUBROUTINE"},
    {0x19e5, "THE 'RECLAIMING' SUBROUTINE"},
    {0x19fb, "THE 'E-LINE-NO' SUBROUTINE"},
    {0x1a1b, "THE 'REPORT AND LINE NUMBER PRINTING' SUBROUTINE"},
    {0x1b17, "THE 'MAIN PARSER' OF THE BASIC INTERPRETER"},
    {0x1b28, "THE STATEMENT LOOP"},
    {0x1b6f, "THE 'SEPARATOR' SUBROUTINE"},
    {0x1b76, "THE 'STMT-RET' SUBROUTINE"},
    {0x1b8a, "THE 'LINE-RUN' ENTRY POINT"},
    {0x1b9e, "THE 'LINE-NEW' SUBROUTINE"},
    {0x1bb2, "THE 'REM' COMMAND ROUTINE"},
    {0x1bb3, "THE 'LINE-END' ROUTINE"},
    {0x1bbf, "THE 'LINE-USE' ROUTINE"},
    {0x1bd1, "THE 'NEXT-LINE' ROUTINE"},
    {0x1bee, "THE 'CHECK-END' SUBROUTINE"},
    {0x1bf4, "THE 'STMT-NEXT' ROUTINE"},
    {0x1c0d, "THE 'COMMAND CLASSES - +00, +03 and +05'"},
    {0x1c1f, "THE 'COMMAND CLASS +01' ROUTINE"},
    {0x1c22, "THE 'VARIABLE IN ASSIGNMENT' SUBROUTINE"},
    {0x1c4e, "THE 'COMMAND CLASS +02' ROUTINE"},
    {0x1c56, "THE 'FETCH A VALUE' SUBROUTINE"},
    {0x1c6c, "THE 'COMMAND CLASS +04' ROUTINE"},
    {0x1c79, "THE 'EXPECT NUMERIC/STRING EXPRESSIONS' SUBROUTINE"},
    {0x1c96, "THE 'SET PERMANENT COLOURS' SUBROUTINE"},
    {0x1cbe, "THE 'COMMAND CLASS +09' ROUTINE"},
    {0x1cdb, "THE 'COMMAND CLASS +0B' ROUTINE"},
    {0x1cde, "THE 'FETCH A NUMBER' SUBROUTINE"},
    {0x1cee, "THE 'STOP' COMMAND ROUTINE"},
    {0x1cf0, "THE 'IF' COMMAND ROUTINE"},
    {0x1d03, "THE 'FOR' COMMAND ROUTINE"},
    {0x1d86, "THE 'LOOK-PROG' SUBROUTINE"},
    {0x1dab, "THE 'NEXT' COMMAND ROUTINE"},
    {0x1dda, "THE 'NEXT-LOOP' SUBROUTINE"},
    {0x1dec, "THE 'READ' COMMAND ROUTINE"},
    {0x1e27, "THE 'DATA' COMMAND ROUTINE"},
    {0x1e39, "THE 'PASS-BY' SUBROUTINE"},
    {0x1e42, "THE 'RESTORE' COMMAND ROUTINE"},
    {0x1e4f, "THE 'RANDOMIZE' COMMAND ROUTINE"},
    {0x1e5f, "THE 'CONTINUE' COMMAND ROUTINE"},
    {0x1e67, "THE 'GO TO' COMMAND ROUTINE"},
    {0x1e7a, "THE 'OUT' COMMAND ROUTINE"},
    {0x1e80, "THE 'POKE' COMMAND ROUTINE"},
    {0x1e85, "THE 'TWO-PARAM' SUBROUTINE"},
    {0x1e94, "THE 'FIND INTEGERS' SUBROUTINE"},
    {0x1ea1, "THE 'RUN' COMMAND ROUTINE"},
    {0x1eac, "THE 'CLEAR' COMMAND ROUTINE"},
    {0x1eed, "THE 'GO SUB' COMMAND ROUTINE"},
    {0x1f05, "THE 'TEST-ROOM' SUBROUTINE"},
    {0x1f23, "THE 'RETURN' COMMAND ROUTINE"},
    {0x1f3a, "THE 'PAUSE' COMMAND ROUTINE"},
    {0x1f54, "THE 'BREAK-KEY' SUBROUTINE"},
    {0x1f60, "THE 'DEF FN' COMMAND ROUTINE"},
    {0x1fc3, "THE 'UNSTACK-Z' SUBROUTINE"},
    {0x1fc9, "THE 'LPRINT and PRINT' COMMAND ROUTINES"},
    {0x1fdf, "THE 'PRINT CONTROLLING' SUBROUTINE"},
    {0x1ff5, "THE 'PRINT A CARRIAGE RETURN' SUBROUTINE"},
    {0x1ffc, "THE 'PRINT ITEMS' SUBROUTINE"},
    {0x2045, "THE 'END OF PRINTING' SUBROUTINE"},
    {0x204e, "THE 'PRINT POSITION' SUBROUTINE"},
    {0x2070, "THE 'ALTER STREAM' SUBROUTINE"},
    {0x2089, "THE 'INPUT' COMMAND ROUTINE"},
    {0x21b9, "THE 'IN-ASSIGN' SUBROUTINE"},
    {0x21d6, "THE 'IN-CHAN-K' SUBROUTINE"},
    {0x21e1, "THE 'COLOUR ITEM' ROUTINES"},
    {0x2294, "THE 'BORDER' COMMAND ROUTINE"},
    {0x22aa, "THE 'PIXEL ADDRESS' SUBROUTINE"},
    {0x22cb, "THE 'POINT' SUBROUTINE"},
    {0x22dc, "THE 'PLOT' COMMAND ROUTINE"},
    {0x2307, "THE 'STK-TO-BC' SUBROUTINE"},
    {0x2314, "THE 'STK-TO-A' SUBROUTINE"},
    {0x2320, "THE 'CIRCLE' COMMAND ROUTINE"},
    {0x2382, "THE 'DRAW' COMMAND ROUTINE"},
    {0x247d, "THE 'INITIAL PARAMETERS' SUBROUTINE"},
    {0x24b7, "THE 'LINE-DRAWING' SUBROUTINE"},
    {0x24fb, "THE 'SCANNING' SUBROUTINE"},
    {0x250f, "THE 'SCANNING QUOTES' SUBROUTINE"},
    {0x2522, "THE 'SCANNING TWO CO-ORDINATES' SUBROUTINE"},
    {0x2530, "THE 'SYNTAX-Z' SUBROUTINE"},
    {0x2535, "THE 'SCANNING SCREEN$' SUBROUTINE"},
    {0x2580, "THE 'SCANNING ATTRIBUTES' SUBROUTINE"},
    {0x25af, "THE 'SCANNING UNARY PLUS' ROUTINE"},
    {0x25b3, "THE 'SCANNING QUOTE' ROUTINE"},
    {0x25e8, "THE 'SCANNING BRACKET' ROUTINE"},
    {0x25f5, "THE 'SCANNING FN' ROUTINE"},
    {0x25f8, "THE 'SCANNING RND' ROUTINE"},
    {0x2627, "THE 'SCANNING PI' ROUTINE"},
    {0x2634, "THE 'SCANNING SCREEN$' ROUTINE"},
    {0x2672, "THE 'SCANNING ATTR' ROUTINE"},
    {0x267b, "THE 'SCANNING POINT' ROUTINE"},
    {0x2684, "THE 'SCANNING ALPHANUMERIC' ROUTINE"},
    {0x268d, "THE 'SCANNING DECIMAL' ROUTINE"},
    {0x26c9, "THE 'SCANNING VARIABLE' ROUTINE"},
    {0x27bd, "THE 'SCANNING FUNCTION' SUBROUTINE"},
    {0x28ab, "THE 'FUNCTION SKIPOVER' SUBROUTINE"},
    {0x28b2, "THE 'LOOK-VARS' SUBROUTINE"},
    {0x2951, "THE 'STACK FUNCTION ARGUMENT' SUBROUTINE"},
    {0x2996, "THE 'STK-VAR' SUBROUTINE"},
    {0x2a52, "THE 'SLICING' SUBROUTINE"},
    {0x2ab1, "THE 'STK-STORE' SUBROUTINE"},
    {0x2acc, "THE 'INT-EXP' SUBROUTINE"},
    {0x2aee, "THE 'DE,(DE+1)' SUBROUTINE"},
    {0x2af4, "THE 'GET-HL*DE' SUBROUTINE"},
    {0x2aff, "THE 'LET' COMMAND ROUTINE"},
    {0x2bf1, "THE 'STK-FETCH' SUBROUTINE"},
    {0x2c02, "THE 'DIM' COMMAND ROUTINE"},
    {0x2c88, "THE 'ALPHANUM' SUBROUTINE"},
    {0x2c8d, "THE 'ALPHA' SUBROUTINE"},
    {0x2c9b, "THE 'DECIMAL TO FLOATING POINT' SUBROUTINE"},
    {0x2d1b, "THE 'NUMERIC' SUBROUTINE"},
    {0x2d22, "THE 'STK-DIGIT' SUBROUTINE"},
    {0x2d28, "THE 'STACK-A' SUBROUTINE"},
    {0x2d2b, "THE 'STACK-BC' SUBROUTINE"},
    {0x2d3b, "THE 'INTEGER TO FLOATING-POINT' SUBROUTINE"},
    {0x2d4f, "THE 'E-FORMAT TO FLOATING-POINT' SUBROUTINE (offset +3C)"},
    {0x2d7f, "THE 'INT-FETCH' SUBROUTINE"},
    {0x2d8e, "THE 'INT-STORE' SUBROUTINE"},
    {0x2da2, "THE 'FLOATING-POINT TO BC' SUBROUTINE"},
    {0x2dc1, "THE 'LOG(2&#8593;A)' SUBROUTINE"},
    {0x2dd5, "THE 'FLOATING-POINT TO A' SUBROUTINE"},
    {0x2de3, "THE 'PRINT A FLOATING-POINT NUMBER' SUBROUTINE"},
    {0x2f8b, "THE 'CA=10*A+C' SUBROUTINE"},
    {0x2f9b, "THE 'PREPARE TO ADD' SUBROUTINE"},
    {0x2fba, "THE 'FETCH TWO NUMBERS' SUBROUTINE"},
    {0x2fdd, "THE 'SHIFT ADDEND' SUBROUTINE"},
    {0x3004, "THE 'ADD-BACK' SUBROUTINE"},
    {0x300f, "THE 'SUBTRACTION' OPERATION (offset +03)"},
    {0x3014, "THE 'ADDITION' OPERATION (offset +0F)"},
    {0x30a9, "THE 'HL=HL*DE' SUBROUTINE"},
    {0x30c0, "THE 'PREPARE TO MULTIPLY OR DIVIDE' SUBROUTINE"},
    {0x30ca, "THE 'MULTIPLICATION' OPERATION (offset +04)"},
    {0x31af, "THE 'DIVISION' OPERATION (offset +05)"},
    {0x3214, "THE 'INTEGER TRUNCATION TOWARDS ZERO' SUBROUTINE (offset +3A)"},
    {0x3293, "THE 'RE-STACK TWO' SUBROUTINE"},
    {0x3297, "THE 'RE-STACK' SUBROUTINE (offset +3D)"},
    {0x335b, "THE 'CALCULATE' SUBROUTINE"},
    {0x33a2, "THE 'SINGLE OPERATION' SUBROUTINE (offset +3B)"},
    {0x33a9, "THE 'TEST 5-SPACES' SUBROUTINE"},
    {0x33b4, "THE 'STACK NUMBER' SUBROUTINE"},
    {0x33c0, "THE 'MOVE A FLOATING-POINT NUMBER' SUBROUTINE (offset +31)"},
    {0x33c6, "THE 'STACK LITERALS' SUBROUTINE (offset +34)"},
    {0x33f7, "THE 'SKIP CONSTANTS' SUBROUTINE"},
    {0x3406, "THE 'MEMORY LOCATION' SUBROUTINE"},
    {0x340f, "THE 'GET FROM MEMORY AREA' SUBROUTINE (offset +41)"},
    {0x341b, "THE 'STACK A CONSTANT' SUBROUTINE (offset +3F)"},
    {0x342d, "THE 'STORE IN MEMORY AREA' SUBROUTINE (offset +40)"},
    {0x343c, "THE 'EXCHANGE' SUBROUTINE (offset +01)"},
    {0x3449, "THE 'SERIES GENERATOR' SUBROUTINE (offset +3E)"},
    {0x346a, "THE 'ABSOLUTE MAGNITUDE' FUNCTION (offset +2A)"},
    {0x346e, "THE 'UNARY MINUS' OPERATION (offset +1B)"},
    {0x3492, "THE 'SIGNUM' FUNCTION (offset +29)"},
    {0x34a5, "THE 'IN' FUNCTION (offset +2C)"},
    {0x34ac, "THE 'PEEK' FUNCTION (offset +2B)"},
    {0x34b3, "THE 'USR' FUNCTION (offset +2D)"},
    {0x34bc, "THE 'USR STRING' FUNCTION (offset +19)"},
    {0x34e9, "THE 'TEST-ZERO' SUBROUTINE"},
    {0x34f9, "THE 'GREATER THAN ZERO' OPERATION (offset +37)"},
    {0x3501, "THE 'NOT' FUNCTION (offset +30)"},
    {0x3506, "THE 'LESS THAN ZERO' OPERATION (offset +36)"},
    {0x350b, "THE 'ZERO OR ONE' SUBROUTINE"},
    {0x351b, "THE 'OR' OPERATION (offset +07)"},
    {0x3524, "THE 'NUMBER AND NUMBER' OPERATION (offset +08)"},
    {0x352d, "THE 'STRING AND NUMBER' OPERATION (offset +10)"},
    {0x353b, "THE 'COMPARISON' OPERATIONS (offsets +09 to +0E, +11 to +16)"},
    {0x359c, "THE 'STRING CONCATENATION' OPERATION (offset +17)"},
    {0x35bf, "THE 'STK-PNTRS' SUBROUTINE"},
    {0x35c9, "THE 'CHR$' FUNCTION (offset +2F)"},
    {0x35de, "THE 'VAL' AND 'VAL$' FUNCTIONS (offsets +18, +1D)"},
    {0x361f, "THE 'STR$' FUNCTION (offset +2E)"},
    {0x3645, "THE 'READ-IN' SUBROUTINE (offset +1A)"},
    {0x3669, "THE 'CODE' FUNCTION (offset +1C)"},
    {0x3674, "THE 'LEN' FUNCTION (offset +1E)"},
    {0x367a, "THE 'DECREASE THE COUNTER' SUBROUTINE (offset +35)"},
    {0x3686, "THE 'JUMP' SUBROUTINE (offset +33)"},
    {0x368f, "THE 'JUMP ON TRUE' SUBROUTINE (offset +00)"},
    {0x369b, "THE 'END-CALC' SUBROUTINE (offset +38)"},
    {0x36a0, "THE 'MODULUS' SUBROUTINE (offset +32)"},
    {0x36af, "THE 'INT' FUNCTION (offset +27)"},
    {0x36c4, "THE 'EXPONENTIAL' FUNCTION (offset +26)"},
    {0x3713, "THE 'NATURAL LOGARITHM' FUNCTION (offset +25)"},
    {0x3783, "THE 'REDUCE ARGUMENT' SUBROUTINE (offset +39)"},
    {0x37aa, "THE 'COSINE' FUNCTION (offset +20)"},
    {0x37b5, "THE 'SINE' FUNCTION (offset +1F)"},
    {0x37da, "THE 'TAN' FUNCTION (offset +21)"},
    {0x37e2, "THE 'ARCTAN' FUNCTION (offset +24)"},
    {0x3833, "THE 'ARCSIN' FUNCTION (offset +22)"},
    {0x3843, "THE 'ARCCOS' FUNCTION (offset +23)"},
    {0x384a, "THE 'SQUARE ROOT' FUNCTION (offset +28)"},
    {0x3851, "THE 'EXPONENTIATION' OPERATION (offset +06)"},
}};

constexpr std::array<sysvar_info, 69> k_sysvars = {{
    {0x5c00, 0x5c07, "KSTATE", "Used in reading the keyboard"},
    {0x5c08, 0x5c08, "LAST-K", "Last key pressed"},
    {0x5c09, 0x5c09, "REPDEL", "Time that a key must be held down before it repeats"},
    {0x5c0a, 0x5c0a, "REPPER", "Delay between successive repeats of a key held down"},
    {0x5c0b, 0x5c0c, "DEFADD", "Address of arguments of user defined function"},
    {0x5c0d, 0x5c0d, "K-DATA", "Second byte of colour controls entered from keyboard"},
    {0x5c0e, 0x5c0f, "TVDATA", "Colour, AT and TAB controls going to television"},
    {0x5c10, 0x5c35, "STRMS", "Addresses of channels attached to streams"},
    {0x5c36, 0x5c37, "CHARS", "256 less than address of character set"},
    {0x5c38, 0x5c38, "RASP", "Length of warning buzz"},
    {0x5c39, 0x5c39, "PIP", "Length of keyboard click"},
    {0x5c3a, 0x5c3a, "ERR-NR", "One less than the error report code"},
    {0x5c3b, 0x5c3b, "FLAGS", "Various flags to control the BASIC system"},
    {0x5c3c, 0x5c3c, "TV-FLAG", "Flags associated with the television"},
    {0x5c3d, 0x5c3e, "ERR-SP", "Address of item on machine stack to use as error return"},
    {0x5c3f, 0x5c40, "LIST-SP", "Return address from automatic listing"},
    {0x5c41, 0x5c41, "MODE", "Specifies K, L, C, E or G cursor"},
    {0x5c42, 0x5c43, "NEWPPC", "Line to be jumped to"},
    {0x5c44, 0x5c44, "NSPPC", "Statement number in line to be jumped to"},
    {0x5c45, 0x5c46, "PPC", "Line number of statement being executed"},
    {0x5c47, 0x5c47, "SUBPPC", "Number within line of statement being executed"},
    {0x5c48, 0x5c48, "BORDCR", "Border colour"},
    {0x5c49, 0x5c4a, "E-PPC", "Number of current line"},
    {0x5c4b, 0x5c4c, "VARS", "Address of variables"},
    {0x5c4d, 0x5c4e, "DEST", "Address of variable in assignment"},
    {0x5c4f, 0x5c50, "CHANS", "Address of channel data"},
    {0x5c51, 0x5c52, "CURCHL", "Address of information used for input and output"},
    {0x5c53, 0x5c54, "PROG", "Address of BASIC program"},
    {0x5c55, 0x5c56, "NXTLIN", "Address of next line in program"},
    {0x5c57, 0x5c58, "DATADD", "Address of terminator of last DATA item"},
    {0x5c59, 0x5c5a, "E-LINE", "Address of command being typed in"},
    {0x5c5b, 0x5c5c, "K-CUR", "Address of cursor"},
    {0x5c5d, 0x5c5e, "CH-ADD", "Address of the next character to be interpreted"},
    {0x5c5f, 0x5c60, "X-PTR", "Address of the character after the '?' marker"},
    {0x5c61, 0x5c62, "WORKSP", "Address of temporary work space"},
    {0x5c63, 0x5c64, "STKBOT", "Address of bottom of calculator stack"},
    {0x5c65, 0x5c66, "STKEND", "Address of start of spare space"},
    {0x5c67, 0x5c67, "BREG", "Calculator's B register"},
    {0x5c68, 0x5c69, "MEM", "Address of area used for calculator's memory"},
    {0x5c6a, 0x5c6a, "FLAGS2", "More flags"},
    {0x5c6b, 0x5c6b, "DF-SZ", "The number of lines in the lower part of the screen"},
    {0x5c6c, 0x5c6d, "S-TOP", "The number of the top program line in automatic listings"},
    {0x5c6e, 0x5c6f, "OLDPPC", "Line number to which CONTINUE jumps"},
    {0x5c70, 0x5c70, "OSPCC", "Number within line of statement to which CONTINUE jumps"},
    {0x5c71, 0x5c71, "FLAGX", "Various flags"},
    {0x5c72, 0x5c73, "STRLEN", "Length of string type destination in assignment"},
    {0x5c74, 0x5c75, "T-ADDR", "Address of next item in parameter table"},
    {0x5c76, 0x5c77, "SEED", "The seed for RND"},
    {0x5c78, 0x5c7a, "FRAMES", "Frame counter"},
    {0x5c7b, 0x5c7c, "UDG", "Address of first user defined graphic"},
    {0x5c7d, 0x5c7e, "COORDS", "Coordinates of last point plotted"},
    {0x5c7f, 0x5c7f, "P-POSN", "Column number of printer position"},
    {0x5c80, 0x5c81, "PR-CC", "Address of next position for LPRINT to print at"},
    {0x5c82, 0x5c83, "ECHO-E", "Column and line number of end of input buffer"},
    {0x5c84, 0x5c85, "DF-CC", "Address in display file of PRINT position"},
    {0x5c86, 0x5c87, "DF-CCL", "Like DF-CC for lower part of screen"},
    {0x5c88, 0x5c89, "S-POSN", "Column and line number for PRINT position"},
    {0x5c8a, 0x5c8b, "S-POSNL", "Like S-POSN for lower part of screen"},
    {0x5c8c, 0x5c8c, "SCR-CT", "Scroll counter"},
    {0x5c8d, 0x5c8d, "ATTR-P", "Permanent current colours"},
    {0x5c8e, 0x5c8e, "MASK-P", "Used for transparent colours"},
    {0x5c8f, 0x5c8f, "ATTR-T", "Temporary current colours"},
    {0x5c90, 0x5c90, "MASK-T", "Temporary transparent colours"},
    {0x5c91, 0x5c91, "P-FLAG", "More flags"},
    {0x5c92, 0x5caf, "MEMBOT", "Calculator's memory area"},
    {0x5cb0, 0x5cb1, "NMIADD", "Non-maskable interrupt address"},
    {0x5cb2, 0x5cb3, "RAMTOP", "Address of last byte of BASIC system area"},
    {0x5cb4, 0x5cb5, "P-RAMT", "Address of last byte of physical RAM"},
    {0x5cb6, 0x5cca, "Channel information", ""},
}};

}  // namespace

const rom_routine_info* lookup_rom_routine(uint16_t addr) {
    const rom_routine_info* best = nullptr;
    for (const auto& info : k_rom_routines) {
        if (info.addr > addr) {
            break;
        }
        best = &info;
    }
    return best;
}

const sysvar_info* lookup_sysvar(uint16_t addr) {
    for (const auto& info : k_sysvars) {
        if (addr >= info.begin && addr <= info.end) {
            return &info;
        }
    }
    return nullptr;
}

std::string format_rom_routine(uint16_t addr) {
    const auto* info = lookup_rom_routine(addr);
    if (!info) {
        return {};
    }
    if (info->addr == addr) {
        return std::string(info->description);
    }
    return std::format("inside {} @ 0x{:04x}", info->description, info->addr);
}

std::string format_sysvar(uint16_t addr) {
    const auto* info = lookup_sysvar(addr);
    if (!info) {
        return {};
    }
    const uint16_t offset = static_cast<uint16_t>(addr - info->begin);
    if (offset == 0) {
        if (info->description.empty()) {
            return std::string(info->name);
        }
        return std::format("{} - {}", info->name, info->description);
    }
    if (info->description.empty()) {
        return std::format("{}+0x{:x}", info->name, offset);
    }
    return std::format("{}+0x{:x} - {}", info->name, offset, info->description);
}

}  // namespace appmake
