#!/usr/bin/env python3
# gen_symbols.py — parse sdldz80 NOI file (full names) and emit a C++
# header with constexpr uint16_t addresses for each exported symbol.
# Falls back to MAP file parsing if NOI is not available.
import sys, re, pathlib

def parse_noi(noi_path):
    """Parse sdldz80 .noi file: 'DEF symbol hex_addr' per line."""
    syms = {}
    noi_re = re.compile(r'^DEF\s+(\S+)\s+0x([0-9A-Fa-f]+)', re.IGNORECASE)
    with open(noi_path) as f:
        for line in f:
            m = noi_re.match(line.strip())
            if m:
                name = m.group(1)
                addr = int(m.group(2), 16)
                if name not in syms:
                    syms[name] = addr
    return syms

def parse_map(map_path):
    """Fallback: parse sdldz80 .map file (names truncated at 9 chars)."""
    syms = {}
    sym_re = re.compile(r'([0-9A-Fa-f]{8})\s+(\S+)')
    with open(map_path) as f:
        for line in f:
            for m in sym_re.finditer(line):
                addr = int(m.group(1), 16)
                name = m.group(2)
                if name.startswith('.') or name.startswith('s__') or \
                   name.startswith('l__') or name == '.__.ABS.':
                    continue
                if name not in syms:
                    syms[name] = addr
    return syms

_SKIP_PREFIXES = ('s__', 'l__', '.__.', '__DATA', '__CODE')
_SKIP_EXACT    = {'s__CODE', 'l__DATA', 'l__CODE', 's__DATA'}

def emit_header(syms, out_path):
    lines = [
        '// runtime_symbols.hpp — auto-generated by gen_symbols.py',
        '// Do not edit by hand.',
        '#pragma once',
        '#include <cstdint>',
        '',
        'namespace rt_sym {',
    ]
    seen_cids = {}
    for name, addr in sorted(syms.items(), key=lambda kv: kv[1]):
        # Skip linker-internal names
        if name in _SKIP_EXACT:
            continue
        if any(name.startswith(p) for p in _SKIP_PREFIXES):
            continue
        # Mangle to a valid C++ identifier: strip leading underscores, replace non-alnum
        cid = name.lstrip('_').replace('.', '_')
        cid = re.sub(r'[^A-Za-z0-9_]', '_', cid)
        if not cid or cid[0].isdigit():
            cid = 'sym_' + cid
        # Skip duplicate C++ identifiers (keep the one that appeared first = lowest addr)
        if cid in seen_cids:
            continue
        seen_cids[cid] = addr
        lines.append(f'    static constexpr uint16_t {cid} = 0x{addr:04X};')
    lines += ['', '} // namespace rt_sym', '']
    pathlib.Path(out_path).write_text('\n'.join(lines))

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(f'usage: {sys.argv[0]} runtime.map runtime_symbols.hpp')
        sys.exit(1)
    map_path = sys.argv[1]
    # Prefer the .noi file (full symbol names); fall back to .map
    noi_path = map_path.replace('.map', '.noi')
    noi_file = pathlib.Path(noi_path)
    if noi_file.exists():
        syms = parse_noi(noi_path)
    else:
        syms = parse_map(map_path)
    emit_header(syms, sys.argv[2])
    print(f'wrote {len(syms)} symbols to {sys.argv[2]}')
